#!/usr/bin/env python3
"""
Build the meta-description backfill SQL from the supplied "Meta Description.xls".

Reads the xls (URL | Meta Description), maps each CMS-collection URL to its
Payload table by slug, and emits an idempotent, transactional SQL file that
OVERWRITES seo_description (+ version_seo_description) for every matched item.
Static / listing pages (not in the CMS) are written to a separate CSV for the
apps/web code update.

Run: python3 migrations/webflow-import/build-meta-desc-import.py <path-to-xls>
"""
from __future__ import annotations

import csv
import os
import re
import sys

import xlrd

EXPORT = os.path.join(os.path.dirname(__file__), "..", "webflow-export")
SQL_OUT = os.path.join(EXPORT, "meta-desc-import.sql")
STATIC_OUT = os.path.join(EXPORT, "meta-desc-static-pages.csv")
NEW_DESC_OUT = os.path.join(EXPORT, "new-meta-descriptions.csv")

# URL prefix -> Payload table
PREFIX_TABLE = {
    "blogs": "blogs", "guide": "guides", "news": "news", "event": "events",
    "resources": "resources", "job": "jobs", "author": "authors",
}


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
        "~/Downloads/Meta Description .xls")
    sheet = xlrd.open_workbook(src).sheet_by_index(0)

    by_table: dict[str, dict[str, str]] = {}
    static: list[tuple[str, str]] = []
    for r in range(1, sheet.nrows):
        url = str(sheet.cell_value(r, 0)).strip()
        desc = str(sheet.cell_value(r, 1)).strip()
        if not url or not desc:
            continue
        path = re.sub(r"^https?://[^/]+", "", url) or "/"
        if len(path) > 1 and path.endswith("/"):
            path = path[:-1]
        parts = path.split("/")
        if len(parts) > 2 and parts[1] in PREFIX_TABLE:
            by_table.setdefault(PREFIX_TABLE[parts[1]], {})["/".join(parts[2:])] = desc
        else:
            static.append((path, desc))

    lines = [
        "-- Meta-description backfill (OVERWRITE all matched CMS items).",
        "-- Generated by build-meta-desc-import.py from 'Meta Description.xls'.",
        "-- Sets ONLY seo_description (+ version_seo_description). Transactional.",
        "BEGIN;",
        "CREATE TEMP TABLE md_seed (tbl text, slug text, descr text) ON COMMIT DROP;",
    ]
    for table, slugs in by_table.items():
        values = ",\n".join(
            f"  ('{table}', {sql_literal(s)}, {sql_literal(d)})"
            for s, d in slugs.items()
        )
        lines.append(f"-- {table}: {len(slugs)} rows")
        lines.append("INSERT INTO md_seed (tbl, slug, descr) VALUES")
        lines.append(values + ";")

    for table in by_table:
        lines.append(f"-- apply {table}")
        lines.append(
            f"UPDATE {table} t SET seo_description = s.descr "
            f"FROM md_seed s WHERE s.tbl = '{table}' AND t.slug = s.slug;"
        )
        lines.append(
            f"UPDATE _{table}_v v SET version_seo_description = s.descr "
            f"FROM md_seed s WHERE s.tbl = '{table}' AND v.version_slug = s.slug;"
        )

    selects = "\nUNION ALL ".join(
        f"SELECT '{t}' AS collection, count(*) FILTER "
        f"(WHERE seo_description IS NOT NULL AND seo_description <> '') AS has_desc, "
        f"count(*) AS total FROM {t}"
        for t in by_table
    )
    lines.append("-- verification")
    lines.append(f"{selects} ORDER BY collection;")
    lines.append("COMMIT;")

    with open(SQL_OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    with open(STATIC_OUT, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["path", "meta_description"])
        for p, d in sorted(static):
            w.writerow([p, d])

    # Per-collection-item new descriptions, for the Excel "New Meta Description" column.
    with open(NEW_DESC_OUT, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["collection", "slug", "new_meta_description"])
        for table, slugs in by_table.items():
            for s, d in sorted(slugs.items()):
                w.writerow([table, s, d])

    total = sum(len(v) for v in by_table.values())
    print(f"[sql] {total} collection-item descriptions -> {SQL_OUT}")
    for t, slugs in sorted(by_table.items()):
        print(f"  {t:10} {len(slugs)}")
    print(f"[csv] {len(static)} static/listing pages -> {STATIC_OUT}")


if __name__ == "__main__":
    main()
