#!/usr/bin/env python3
"""
Build SEO backfill artifacts from the fresh Webflow export.

Reads migrations/webflow-export/raw/*.jsonl and emits:
  1. migrations/webflow-export/seo-extract.csv  — every item, all 12 collections
     (collection, slug, name, meta_title, meta_description). Source of truth for
     the Excel deliverable. Blank meta is left empty in the CSV.
  2. migrations/webflow-export/seo-import.sql    — idempotent, transactional
     backfill that sets ONLY seo_title / seo_description on the 6 collections
     Webflow actually stored meta for, on both the main table and its `_v`
     version table. Webflow-blank => SQL NULL (so the web layer's
     `seo.title ?? title` fallback fires). All other seo_* sibling columns are
     left untouched.

Run:  python3 migrations/webflow-import/build-seo-artifacts.py
"""
from __future__ import annotations

import csv
import json
import os

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "webflow-export", "raw")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "webflow-export")

# Webflow collection (export filename stem) -> Payload table name.
# Only the 6 collections that carry meta in Webflow are imported into the DB.
META_COLLECTIONS: dict[str, str] = {
    "blogs": "blogs",
    "news": "news",
    "guides": "guides",
    "events": "events",
    "jobs": "jobs",
    "authors": "authors",
}

# All 12 collections appear in the extract CSV / Excel (no-meta ones show blank).
ALL_COLLECTIONS = [
    "blogs", "news", "guides", "events", "jobs", "authors",
    "resources", "webinars", "categories", "newsCategories",
    "jobLocations", "aboutGalleries",
]


def clean(value: object) -> str:
    """Normalize a meta value to a trimmed plain string ('' when absent)."""
    if value is None:
        return ""
    return str(value).strip()


def read_collection(stem: str) -> list[dict[str, str]]:
    path = os.path.join(RAW_DIR, f"{stem}.jsonl")
    rows: list[dict[str, str]] = []
    if not os.path.exists(path):
        return rows
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            meta = d.get("_meta") or {}
            rows.append({
                "collection": stem,
                "slug": clean(d.get("slug")),
                "name": clean(d.get("name")),
                "meta_title": clean(d.get("meta-title")),
                "meta_description": clean(d.get("meta-description")),
                "created": clean(meta.get("createdOn"))[:10],
                "last_updated": clean(meta.get("lastUpdated"))[:10],
                "last_published": clean(meta.get("lastPublished"))[:10],
            })
    return rows


def sql_literal(value: str) -> str:
    """Postgres string literal, or NULL for blank (standard_conforming_strings)."""
    if value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def build_csv(all_rows: dict[str, list[dict[str, str]]]) -> None:
    out = os.path.join(OUT_DIR, "seo-extract.csv")
    with open(out, "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["collection", "slug", "name", "meta_title", "meta_description",
                    "created", "last_updated", "last_published"])
        for stem in ALL_COLLECTIONS:
            for r in all_rows.get(stem, []):
                w.writerow([r["collection"], r["slug"], r["name"],
                            r["meta_title"], r["meta_description"],
                            r["created"], r["last_updated"], r["last_published"]])
    print(f"[csv] wrote {out}")


def build_sql(all_rows: dict[str, list[dict[str, str]]]) -> None:
    out = os.path.join(OUT_DIR, "seo-import.sql")
    lines: list[str] = []
    lines.append("-- Webflow meta-title/meta-description backfill (exact values).")
    lines.append("-- Generated by build-seo-artifacts.py. Idempotent. Transactional.")
    lines.append("-- Sets ONLY seo_title / seo_description (+ version_* mirror).")
    lines.append("-- Webflow-blank => NULL. Run: psql -f seo-import.sql")
    lines.append("BEGIN;")
    lines.append("CREATE TEMP TABLE wf_seo (")
    lines.append("  collection text, slug text, mt text, md text")
    lines.append(") ON COMMIT DROP;")

    for stem, table in META_COLLECTIONS.items():
        rows = [r for r in all_rows.get(stem, []) if r["slug"]]
        if not rows:
            continue
        lines.append(f"-- {stem}: {len(rows)} rows")
        values = ",\n".join(
            f"  ('{stem}', {sql_literal(r['slug'])}, "
            f"{sql_literal(r['meta_title'])}, {sql_literal(r['meta_description'])})"
            for r in rows
        )
        lines.append("INSERT INTO wf_seo (collection, slug, mt, md) VALUES")
        lines.append(values + ";")

    for stem, table in META_COLLECTIONS.items():
        lines.append(f"-- apply {stem} -> {table}")
        lines.append(
            f"UPDATE {table} t SET seo_title = s.mt, seo_description = s.md "
            f"FROM wf_seo s WHERE s.collection = '{stem}' AND t.slug = s.slug;"
        )
        lines.append(
            f"UPDATE _{table}_v v SET version_seo_title = s.mt, "
            f"version_seo_description = s.md "
            f"FROM wf_seo s WHERE s.collection = '{stem}' "
            f"AND v.version_slug = s.slug;"
        )

    # Jobs: Webflow stores zero meta-descriptions (0/60), so the exact value
    # for EVERY job description is NULL. A handful of job rows were re-slugged
    # by Payload (Webflow `foo--bar` -> `foo-bar`) and so miss the slug join
    # above, leaving a stale `job-summary` fallback in seo_description. Clear
    # unconditionally to guarantee exact Webflow parity.
    lines.append("-- jobs: guarantee zero descriptions (exact Webflow; clears slug-normalized rows)")
    lines.append("UPDATE jobs SET seo_description = NULL WHERE seo_description IS NOT NULL;")
    lines.append("UPDATE _jobs_v SET version_seo_description = NULL "
                 "WHERE version_seo_description IS NOT NULL;")

    # Verification report inside the same transaction.
    lines.append("-- verification")
    selects = "\nUNION ALL ".join(
        f"SELECT '{table}' AS collection, count(*) AS total, "
        f"count(seo_title) FILTER (WHERE seo_title IS NOT NULL) AS has_title, "
        f"count(seo_description) FILTER (WHERE seo_description IS NOT NULL) AS has_desc "
        f"FROM {table}"
        for table in META_COLLECTIONS.values()
    )
    lines.append(f"{selects} ORDER BY collection;")
    lines.append("COMMIT;")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"[sql] wrote {out}")


def main() -> None:
    all_rows = {stem: read_collection(stem) for stem in ALL_COLLECTIONS}
    total = sum(len(v) for v in all_rows.values())
    print(f"[read] {total} items across {len(all_rows)} collections")
    build_csv(all_rows)
    build_sql(all_rows)


if __name__ == "__main__":
    main()
