/**
 * H2 — Schema parity audit
 *
 * Compares Webflow field names (from exported JSONL sample) against
 * Payload collection field names and writes a markdown table.
 *
 * Usage:
 *   tsx migrations/webflow-import/schema-parity-audit.ts
 *
 * Input:  migrations/webflow-export/raw/<collection>.jsonl
 * Output: migrations/SCHEMA-PARITY-AUDIT.md
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';

const RAW_DIR = path.resolve('migrations/webflow-export/raw');
const OUT_FILE = path.resolve('migrations/SCHEMA-PARITY-AUDIT.md');

/**
 * Hand-maintained mapping: webflow field name → payload field path.
 * `null` = intentionally dropped. `'—'` = no direct equivalent (manual review).
 */
const FIELD_MAP: Record<string, Record<string, string | null>> = {
  blogs: {
    name: 'title',
    slug: 'slug',
    'post-body': 'body',
    'post-summary': 'abstract',
    'thumbnail-image': 'heroImage',
    'featured-post': 'featured',
    'main-image': 'heroImage',
    'author-2': 'authors',
    tags: 'categories',
    'date-published': 'publishedAt',
    'read-time': null, // computed
  },
  news: {
    name: 'title',
    slug: 'slug',
    'post-body': 'body',
    'post-summary': 'abstract',
    'thumbnail-image': 'heroImage',
    'publication-date': 'publicationDate',
    'news-category': 'newsCategories',
  },
  guides: {
    name: 'title',
    slug: 'slug',
    body: 'body',
    summary: 'abstract',
    image: 'heroImage',
    'guide-category': 'categories',
    'date-published': 'publishedAt',
    authors: 'authors',
  },
  resources: {
    name: 'title',
    slug: 'slug',
    description: 'abstract',
    'resource-type': 'resourceType',
    image: 'heroImage',
    'download-url': 'downloadUrl',
  },
  events: {
    name: 'title',
    slug: 'slug',
    description: 'abstract',
    location: 'location',
    'start-date': 'startDate',
    'end-date': 'endDate',
    image: 'heroImage',
    'registration-link': 'registrationUrl',
  },
  webinars: {
    name: 'title',
    slug: 'slug',
    description: 'abstract',
    'date-time': 'startDate',
    'recording-url': 'recordingUrl',
    image: 'heroImage',
    speakers: 'authors',
  },
  jobs: {
    name: 'title',
    slug: 'slug',
    description: 'body',
    location: 'jobLocations',
    type: 'jobType',
    department: 'department',
    'apply-url': 'applyUrl',
  },
  authors: {
    name: 'name',
    slug: 'slug',
    bio: 'bio',
    photo: 'photo',
    title: 'jobTitle',
    twitter: 'socialLinks',
    linkedin: 'socialLinks',
  },
};

const collectWebflowFields = async (jsonlFile: string): Promise<Set<string>> => {
  const fields = new Set<string>();
  if (!fs.existsSync(jsonlFile)) return fields;

  const rl = readline.createInterface({ input: fs.createReadStream(jsonlFile) });
  let lines = 0;
  for await (const line of rl) {
    if (lines > 20) break; // sample first 20 rows
    lines += 1;
    try {
      const row = JSON.parse(line) as Record<string, unknown>;
      for (const key of Object.keys(row)) {
        if (!['collection', 'webflowId', 'id'].includes(key)) fields.add(key);
      }
    } catch {
      // ignore malformed lines
    }
  }
  return fields;
};

const run = async (): Promise<void> => {
  console.log('[schema-parity] Generating audit…');

  const lines: string[] = [
    '# Schema Parity Audit — Webflow → Payload',
    '',
    '_Auto-generated by `migrations/webflow-import/schema-parity-audit.ts`._',
    '',
    'Status key: **mapped** = explicit mapping exists | **missing** = no Payload field found | **dropped** = intentionally excluded | **new** = Payload field with no Webflow source',
    '',
  ];

  const collectionSlugs = Object.keys(FIELD_MAP);

  for (const slug of collectionSlugs) {
    const jsonlFile = path.join(RAW_DIR, `${slug}.jsonl`);
    const webflowFields = await collectWebflowFields(jsonlFile);
    const mappings = FIELD_MAP[slug] ?? {};

    lines.push(`## ${slug}`, '');
    lines.push('| Webflow field | Payload field | Status |');
    lines.push('|---|---|---|');

    // Fields from JSONL sample
    const allWebflowFields = new Set([...Object.keys(mappings), ...webflowFields]);
    for (const wfField of allWebflowFields) {
      const payloadField = mappings[wfField];
      if (payloadField === undefined) {
        lines.push(`| \`${wfField}\` | — | **missing** |`);
      } else if (payloadField === null) {
        lines.push(`| \`${wfField}\` | _(dropped)_ | **dropped** |`);
      } else {
        lines.push(`| \`${wfField}\` | \`${payloadField}\` | **mapped** |`);
      }
    }
    lines.push('');
  }

  fs.writeFileSync(OUT_FILE, lines.join('\n'));
  console.log(`[schema-parity] Written to ${OUT_FILE}`);
};

run().catch((err) => {
  console.error('[schema-parity] Fatal:', err);
  process.exit(1);
});
