/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    newsCategories: NewsCategory;
    jobLocations: JobLocation;
    forms: Form;
    blogs: Blog;
    news: News;
    guides: Guide;
    resources: Resource;
    events: Event;
    webinars: Webinar;
    jobs: Job;
    aboutGalleries: AboutGallery;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    newsCategories: NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    jobLocations: JobLocationsSelect<false> | JobLocationsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    webinars: WebinarsSelect<false> | WebinarsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    aboutGalleries: AboutGalleriesSelect<false> | AboutGalleriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Composite roles supported. Author = own drafts only. Editor = publish content. Admin = full access.
   */
  roles: ('admin' | 'editor' | 'author')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Storage folder. Re-classify if the upload was placed in the wrong bucket.
   */
  folder?:
    | (
        | 'web/blog'
        | 'web/news'
        | 'web/guide'
        | 'web/resource'
        | 'web/event'
        | 'web/webinar'
        | 'web/job'
        | 'web/author'
        | 'web/about'
        | 'web/page'
        | 'web/general'
      )
    | null;
  /**
   * Purely decorative image (no informational content). When true, alt text is hidden and the image renders with empty alt per WCAG 2.2 SC 1.1.1.
   */
  decorative?: boolean | null;
  /**
   * Required for non-decorative images. Pre-filled from the humanised filename — review before publish.
   */
  alt?: string | null;
  /**
   * Optional caption shown beneath the image where supported.
   */
  caption?: string | null;
  /**
   * Photographer / source attribution.
   */
  credit?: string | null;
  /**
   * Smart-crop focal point as percentages (0–100). Drives OG-image and 1:1 thumbnail crops.
   */
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL-safe slug. Auto-generated from "name" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  photo?: (number | null) | Media;
  /**
   * Job title shown on the byline + Person JSON-LD.
   */
  role?: string | null;
  location?: string | null;
  /**
   * One-line bio for cards and SERP snippets.
   */
  bioShort?: string | null;
  /**
   * Full bio shown on /author/[slug].
   */
  bioLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Topics this author covers. Powers Person JSON-LD knowsAbout and "more from this author on X" suggestions.
   */
  topicAreas?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
    website?: string | null;
    email?: string | null;
  };
  education?:
    | {
        institution: string;
        degree?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  experience?:
    | {
        company: string;
        role?: string | null;
        fromYear?: number | null;
        toYear?: number | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        title: string;
        issuer?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Toggle off to hide this author from the byline picker on new drafts. Existing bylines stay intact.
   */
  acceptingNewBylines?: boolean | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-safe slug. Auto-generated from "name" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  /**
   * Optional parent category for hierarchical taxonomies.
   */
  parent?: (number | null) | Category;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsCategories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  /**
   * URL-safe slug. Auto-generated from "name" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  /**
   * Optional parent category for hierarchical taxonomies.
   */
  parent?: (number | null) | NewsCategory;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobLocations".
 */
export interface JobLocation {
  id: number;
  name: string;
  /**
   * URL-safe slug. Auto-generated from "name" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  type: 'country' | 'region' | 'city';
  /**
   * ISO 3166-1 alpha-2 country code (e.g. IN, US, GB). Two uppercase letters.
   */
  isoCountry: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  /**
   * URL-safe slug. Auto-generated from "name" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  /**
   * Internal notes for editors. Not shown to visitors.
   */
  description?: string | null;
  /**
   * Forms with more than 7 fields show measurably higher abandonment per Baymard — consider conditional logic or splitting into multiple steps.
   */
  fields: {
    /**
     * Machine name. Becomes the JSON key on the lead record.
     */
    name: string;
    type: 'text' | 'email' | 'textarea' | 'select' | 'checkbox' | 'consent';
    /**
     * Visitor-facing label.
     */
    label?: string | null;
    /**
     * Consent fields are always required and cannot be unchecked here.
     */
    required?: boolean | null;
    placeholder?: string | null;
    helpText?: string | null;
    defaultValue?: string | null;
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Exact text the visitor sees + agrees to. Snapshotted onto every lead record at submit time for GDPR audit defensibility.
     */
    consentText?: string | null;
    /**
     * Server-enforced via Zod at submit time.
     */
    validation?: {
      minLength?: number | null;
      maxLength?: number | null;
      /**
       * Regular expression source (no leading/trailing slashes).
       */
      pattern?: string | null;
    };
    /**
     * Show this field only when the rules below match. Reduces form abandonment by 8–15% per Baymard research.
     */
    conditions?: {
      mode?: ('all' | 'any') | null;
      rules?:
        | {
            fieldName: string;
            operator: 'equals' | 'notEquals' | 'contains';
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Override the default validation error. Defaults are inlined per validation type in the form renderer.
     */
    errorMessage?: string | null;
    id?: string | null;
  }[];
  submitLabel?: string | null;
  postSubmit: {
    kind: 'message' | 'redirect';
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    url?: string | null;
  };
  /**
   * CRM handlers fan out in parallel to the DB write. Handler config (API keys, list IDs) lives in env. Adapter implementations land in Phase E.
   */
  crmHandlers?: ('hubspot' | 'salesforce')[] | null;
  /**
   * Email addresses that receive the new-lead notification.
   */
  notifyTo?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * System-managed. Auto-increments when fields[] changes after the form has at least one submission.
   */
  schemaVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  /**
   * Drives the SEO description fallback. Aim for ≤ 160 characters.
   */
  abstract?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Multi-author supported — every byline is credited in JSON-LD author[]. Defaults to current user on draft create (Phase D hook).
   */
  authors?: (number | Author)[] | null;
  /**
   * Author who reviewed this post for accuracy. Surfaced in JSON-LD reviewedBy + Person — high-leverage E-E-A-T signal.
   */
  reviewedBy?: (number | null) | Author;
  /**
   * Date of the most recent review pass. When unset, falls back to updatedAt with a note in the SEO panel.
   */
  lastReviewedAt?: string | null;
  categories?: (number | Category)[] | null;
  /**
   * Optional. When non-empty, emits FAQPage JSON-LD on the rendered page.
   */
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Manually curated. Empty = listing component picks by category.
   */
  relatedPosts?: (number | Blog)[] | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  /**
   * Computed from body word count on save (Phase D hook).
   */
  readingMinutes?: number | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  abstract?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: (number | Author)[] | null;
  newsCategories?: (number | NewsCategory)[] | null;
  /**
   * Optional. For press pickups / coverage on external outlets.
   */
  externalUrl?: string | null;
  /**
   * Defaults to now on first publish.
   */
  publicationDate: string;
  relatedNews?: (number | News)[] | null;
  /**
   * Computed from body word count on save (Phase D hook).
   */
  readingMinutes?: number | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: (number | Author)[] | null;
  /**
   * Author who reviewed this guide. Surfaced in JSON-LD reviewedBy + Person — high-leverage E-E-A-T signal.
   */
  reviewedBy?: (number | null) | Author;
  /**
   * Editorial-freshness signal. Surfaced in JSON-LD dateReviewed.
   */
  lastReviewedAt?: string | null;
  /**
   * Replaces Webflow Q1…Q5 / Ans1…Ans5. Drives FAQPage JSON-LD when non-empty.
   */
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Replaces Webflow Article About 1…8.
   */
  articleSections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Replaces Webflow Article Mentions 1…10. Each citation surfaces in JSON-LD citation[].
   */
  citations?:
    | {
        label: string;
        source?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Replaces Webflow Article keyword 1…10. Surfaced in JSON-LD mentions[] as Thing entities (AEO/GEO signal).
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  relatedGuides?: (number | Guide)[] | null;
  /**
   * Computed from body word count on save (Phase D hook).
   */
  readingMinutes?: number | null;
  wordCount?: number | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  type?: ('whitepaper' | 'report' | 'brief' | 'datasheet' | 'case-study') | null;
  heroImage?: (number | null) | Media;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * PDF or other downloadable. Routed to web/resource/.
   */
  asset?: (number | null) | Media;
  /**
   * When enabled, the asset download requires a form submission. Sets accessLevel to lead-gated by default.
   */
  gated?: boolean | null;
  /**
   * Form the visitor fills to unlock the download.
   */
  gateForm?: (number | null) | Form;
  accessLevel?: ('public' | 'lead-gated' | 'customer-only') | null;
  /**
   * Incremented on every successful download (Phase E hook).
   */
  downloadCount?: number | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  venue: string;
  abstract?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * IANA timezone string (e.g. Asia/Kolkata). Falls back to siteSettings.organizationTimezone.
   */
  timezone?: string | null;
  /**
   * Override for vague dates ("Q3 2026", "Spring 2027").
   */
  customDateLabel?: string | null;
  /**
   * Per-record switchable per locked schema decision.
   */
  registrationMode: 'internal' | 'external';
  registrationUrl?: string | null;
  registrationForm?: (number | null) | Form;
  attendeesCap?: number | null;
  /**
   * Agenda PDF (routed to web/event/).
   */
  agendaPdf?: (number | null) | Media;
  /**
   * Post-event photos. Surface only after the event ends.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  heroImage?: (number | null) | Media;
  abstract?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  webinarType: 'live' | 'on-demand' | 'panel' | 'demo';
  region: 'Americas' | 'EMEA' | 'APAC' | 'Global';
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * Falls back to siteSettings.organizationTimezone.
   */
  timezone?: string | null;
  registrationMode: 'internal' | 'external';
  registrationUrl?: string | null;
  registrationForm?: (number | null) | Form;
  attendeesCap?: number | null;
  speakers?: (number | Author)[] | null;
  /**
   * Slides PDF (routed to web/webinar/).
   */
  pdf?: (number | null) | Media;
  /**
   * Post-event recording. Surfaces after endsAt < now.
   */
  recordingUrl?: string | null;
  /**
   * External slides link. Use the pdf field instead when hosting on R2.
   */
  slidesUrl?: string | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * URL-safe slug. Auto-generated from "title" on first save; safe to edit later (a redirect row is created automatically when you do).
   */
  slug: string;
  source: 'cms' | 'ats';
  /**
   * Deep link into the external ATS. Required when source=ats.
   */
  atsUrl?: string | null;
  department?:
    | ('engineering' | 'sales' | 'marketing' | 'customer-success' | 'operations' | 'finance' | 'legal' | 'people')
    | null;
  employmentType?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
  experienceLevel?: ('entry' | 'mid' | 'senior' | 'staff' | 'principal') | null;
  /**
   * Optional when remote=true. Phase D hook auto-fills "Remote (Global)" sentinel.
   */
  locations?: (number | JobLocation)[] | null;
  remote?: boolean | null;
  salaryRange?: {
    min?: number | null;
    max?: number | null;
    currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional JD PDF (routed to web/job/).
   */
  descriptionPdf?: (number | null) | Media;
  /**
   * mailto:hire@cleanstart.com is acceptable.
   */
  applyUrl?: string | null;
  status?: ('open' | 'paused' | 'closed') | null;
  /**
   * Defaults to publishedAt + 90 days on first publish (Phase D hook).
   */
  applicationDeadline?: string | null;
  /**
   * Default applicationDeadline + 7 days. Auto-close cron uses this.
   */
  expiresAt?: string | null;
  closedAt?: string | null;
  /**
   * On-page SEO surface. Most fields auto-fall-back from typed document fields and site defaults; only override when you have a specific reason.
   */
  seo?: {
    /**
     * SEO title. Falls back to the document title + site default. Aim for ≤ 60 characters.
     */
    title?: string | null;
    /**
     * SEO description. Falls back to the document abstract / first paragraph. Aim for ≤ 160 characters.
     */
    description?: string | null;
    /**
     * When set to no-index, the page is excluded from /sitemap.xml and Google won't show it.
     */
    indexable?: ('index' | 'noindex' | 'noindex,nofollow') | null;
    /**
     * Falls back to the hero image, then the site default OG image. Derivatives served at 1200×630 (OGP) and 1200×675 (Discover).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override for the og:image alt text. Falls back to the alt text on the linked media asset.
     */
    ogImageAlt?: string | null;
    /**
     * Show fields to override the og:title / og:description independently of the SEO title / description.
     */
    useAdvancedOg?: boolean | null;
    /**
     * Defaults to the SEO title. Most editors never need to override this.
     */
    ogTitle?: string | null;
    /**
     * Defaults to the SEO description.
     */
    ogDescription?: string | null;
    /**
     * Only enable when this content was originally published elsewhere and you want Google to credit the original URL. For duplicate pages on cleanstart.com, use a redirect instead.
     */
    useCustomCanonical?: boolean | null;
    /**
     * Off-domain canonical URL (HTTPS, no query/fragment). Validated at save time. Every change writes an audit row.
     */
    canonicalOverride?: string | null;
    /**
     * CSS selectors marking paragraphs eligible for Schema.org Speakable JSON-LD (voice assistants and AI agents reading aloud). Empty = the lead + first body paragraph are auto-marked.
     */
    speakablePath?:
      | {
          selector: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Image rows shown on /about-us. Each item is NOT URL-addressable — only /about-us reads this collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutGalleries".
 */
export interface AboutGallery {
  id: number;
  name: string;
  /**
   * Internal-only slug. Not URL-addressable.
   */
  slug: string;
  image: number | Media;
  caption?: string | null;
  /**
   * Drag to reorder in the list view (Phase D admin UX).
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'newsCategories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'jobLocations';
        value: number | JobLocation;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'webinars';
        value: number | Webinar;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'aboutGalleries';
        value: number | AboutGallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  folder?: T;
  decorative?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  role?: T;
  location?: T;
  bioShort?: T;
  bioLong?: T;
  topicAreas?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        website?: T;
        email?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        year?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        company?: T;
        role?: T;
        fromYear?: T;
        toYear?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        title?: T;
        issuer?: T;
        year?: T;
        id?: T;
      };
  acceptingNewBylines?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  parent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsCategories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  parent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobLocations_select".
 */
export interface JobLocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  isoCountry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        label?: T;
        required?: T;
        placeholder?: T;
        helpText?: T;
        defaultValue?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        consentText?: T;
        validation?:
          | T
          | {
              minLength?: T;
              maxLength?: T;
              pattern?: T;
            };
        conditions?:
          | T
          | {
              mode?: T;
              rules?:
                | T
                | {
                    fieldName?: T;
                    operator?: T;
                    value?: T;
                    id?: T;
                  };
            };
        errorMessage?: T;
        id?: T;
      };
  submitLabel?: T;
  postSubmit?:
    | T
    | {
        kind?: T;
        body?: T;
        url?: T;
      };
  crmHandlers?: T;
  notifyTo?:
    | T
    | {
        email?: T;
        id?: T;
      };
  schemaVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  abstract?: T;
  heroImage?: T;
  body?: T;
  authors?: T;
  reviewedBy?: T;
  lastReviewedAt?: T;
  categories?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedPosts?: T;
  featured?: T;
  pinned?: T;
  readingMinutes?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  abstract?: T;
  heroImage?: T;
  body?: T;
  authors?: T;
  newsCategories?: T;
  externalUrl?: T;
  publicationDate?: T;
  relatedNews?: T;
  readingMinutes?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  body?: T;
  authors?: T;
  reviewedBy?: T;
  lastReviewedAt?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  articleSections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  citations?:
    | T
    | {
        label?: T;
        source?: T;
        url?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  relatedGuides?: T;
  readingMinutes?: T;
  wordCount?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  heroImage?: T;
  summary?: T;
  body?: T;
  asset?: T;
  gated?: T;
  gateForm?: T;
  accessLevel?: T;
  downloadCount?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  venue?: T;
  abstract?: T;
  heroImage?: T;
  body?: T;
  startsAt?: T;
  endsAt?: T;
  timezone?: T;
  customDateLabel?: T;
  registrationMode?: T;
  registrationUrl?: T;
  registrationForm?: T;
  attendeesCap?: T;
  agendaPdf?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  abstract?: T;
  body?: T;
  webinarType?: T;
  region?: T;
  startsAt?: T;
  endsAt?: T;
  timezone?: T;
  registrationMode?: T;
  registrationUrl?: T;
  registrationForm?: T;
  attendeesCap?: T;
  speakers?: T;
  pdf?: T;
  recordingUrl?: T;
  slidesUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  source?: T;
  atsUrl?: T;
  department?: T;
  employmentType?: T;
  experienceLevel?: T;
  locations?: T;
  remote?: T;
  salaryRange?:
    | T
    | {
        min?: T;
        max?: T;
        currency?: T;
      };
  body?: T;
  descriptionPdf?: T;
  applyUrl?: T;
  status?: T;
  applicationDeadline?: T;
  expiresAt?: T;
  closedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        indexable?: T;
        ogImage?: T;
        ogImageAlt?: T;
        useAdvancedOg?: T;
        ogTitle?: T;
        ogDescription?: T;
        useCustomCanonical?: T;
        canonicalOverride?: T;
        speakablePath?:
          | T
          | {
              selector?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutGalleries_select".
 */
export interface AboutGalleriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  caption?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'guides';
          value: number | Guide;
        } | null)
      | ({
          relationTo: 'resources';
          value: number | Resource;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'webinars';
          value: number | Webinar;
        } | null)
      | ({
          relationTo: 'jobs';
          value: number | Job;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}