#!/usr/bin/env -S node --no-warnings --experimental-strip-types
/**
 * Renders every entry in the email registry to `apps/cms/emails/`.
 *
 * The HTML is generated, not authored: `lib/email/layout.ts` and the builders
 * remain the source of truth. Committing the output makes an email design
 * change visible as a reviewable diff instead of vanishing inside a template
 * function, and gives anyone a file to open in a browser or paste into a
 * client-rendering test without running the CMS.
 *
 * Run from apps/cms:
 *   pnpm exec tsx scripts/render-email-templates.ts
 *   pnpm exec tsx scripts/render-email-templates.ts --check   # CI drift gate
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { EMAIL_TEMPLATES } from '../src/payload/lib/email/registry.ts';

const OUT_DIR = path.resolve(import.meta.dirname, '..', 'emails');

const indexPage = (rows: { key: string; subject: string; form: string; audience: string }[]): string =>
  `<!doctype html>
<html lang="en"><meta charset="utf-8"><title>CleanStart email templates</title>
<style>
 body{margin:0;font:14px/1.6 Arial,Helvetica,sans-serif;background:#f1f5f9;color:#0f172a;padding:40px 24px}
 main{max-width:900px;margin:0 auto}
 h1{font-size:22px;margin:0 0 6px}p.sub{margin:0 0 28px;color:#64748b}
 table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}
 th,td{text-align:left;padding:12px 16px;border-bottom:1px solid #e2e8f0;font-size:13px;vertical-align:top}
 th{background:#f8fafc;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#64748b}
 tr:last-child td{border-bottom:0}
 a{color:#3960f9}
 .tag{display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:700}
 .visitor{background:#eef2ff;color:#3960f9}.internal{background:#f1f5f9;color:#64748b}
</style>
<main>
<h1>CleanStart email templates</h1>
<p class="sub">Generated from the code builders. Do not edit these files by hand.</p>
<table><tr><th>Template</th><th>Form</th><th>Audience</th><th>Subject</th></tr>
${rows
  .map(
    (r) =>
      `<tr><td><a href="./${r.key}.html">${r.key}</a></td><td>${r.form}</td><td><span class="tag ${r.audience}">${r.audience}</span></td><td>${r.subject}</td></tr>`,
  )
  .join('\n')}
</table>
</main></html>`;

const run = (): void => {
  const check = process.argv.includes('--check');
  const rendered = new Map<string, string>();

  for (const entry of EMAIL_TEMPLATES) {
    if (entry.key === 'payload-password-reset') continue; // Rendered by Payload, not by us.
    const { subject, htmlContent } = entry.sample();
    rendered.set(
      `${entry.key}.html`,
      `<!-- Generated by scripts/render-email-templates.ts. Do not edit.
     Source: ${entry.sentFrom}
     Form:   ${entry.form}
     Subject: ${subject} -->\n${htmlContent}\n`,
    );
  }
  rendered.set(
    'index.html',
    indexPage(
      EMAIL_TEMPLATES.filter((e) => e.key !== 'payload-password-reset').map((e) => ({
        key: e.key,
        subject: e.sample().subject,
        form: e.form,
        audience: e.audience,
      })),
    ),
  );

  if (check) {
    let drift = 0;
    for (const [name, body] of rendered) {
      let current = '';
      try {
        current = readFileSync(path.join(OUT_DIR, name), 'utf8');
      } catch {
        current = '';
      }
      if (current !== body) {
        console.error(`drift: ${name}`);
        drift += 1;
      }
    }
    if (drift > 0) {
      console.error(`\n${drift} file(s) out of date. Run: pnpm exec tsx scripts/render-email-templates.ts`);
      process.exit(1);
    }
    console.log(`emails/ is up to date (${rendered.size} files).`);
    return;
  }

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, body] of rendered) writeFileSync(path.join(OUT_DIR, name), body);
  console.log(`Wrote ${readdirSync(OUT_DIR).length} files to apps/cms/emails/`);
};

run();
