// Cross-app role enum. Re-exported by apps/cms and consumed by apps/web
// once it lands. The canonical Payload type surface lives in
// `apps/cms/src/payload-types.ts` (regenerated by `payload generate:types`);
// importing from there is fine for cms-internal code, while this package
// stays as the single shared module for cross-app constants.

// `seo` — a structured-data/SEO operator who may edit Schema.org overrides
// (seo.additionalSchema, pageRegistry) site-wide without full admin. Sits
// between editor and admin for SEO surfaces only.
export const ROLES = ['admin', 'editor', 'author', 'seo'] as const;
export type Role = (typeof ROLES)[number];
