// AUTO-GENERATED by scripts/gen-legal-seed.mjs from the legacy static legal
// pages. Content source of truth for seed-legal.ts. Edit here going forward.

export interface LegalSeedDoc {
  title: string;
  slug: string;
  order: number;
  icon: string;
  /** ISO date the terms take effect; stamped onto effectiveDate + publishedAt. */
  effectiveDate: string;
  /** Document body as HTML; converted to Lexical at seed time (htmlToLexical). */
  html: string;
}

export const LEGAL_SEED: LegalSeedDoc[] = [
  {
    title: "Additional Third-Party Terms",
    slug: "additional-third-party-terms",
    order: 1,
    icon: "FileText",
    effectiveDate: "2026-06-04",
    html: `
<p><em>(for Integrated Services)</em></p>
            <h3>1. Purpose</h3>
            <p>
              This Third-Party Software and Open Source Components Policy (this &ldquo;Policy&rdquo;)
              describes the third-party software components, including open source software, that
              may be included in or accessed through Cleanstart, Inc. (&ldquo;Cleanstart&rdquo;, the
              &ldquo;Company&rdquo;) products and services. This Policy supplements the Master
              Service and License Agreement (the &ldquo;MSA&rdquo;) and the Service Level Agreement
              (the &ldquo;SLA&rdquo;) between Cleanstart and the customer (the &ldquo;Customer&rdquo;),
              and is intended to provide transparency regarding the composition, licensing, and
              provenance of Cleanstart products and to clarify the respective rights and
              responsibilities of Cleanstart and Customer with respect to such components.
              Capitalised terms used but not defined in this Policy have the meanings given in the
              MSA.
            </p>
            <p>
              In the event of any conflict between this Policy and the MSA, the MSA shall control
              with respect to the subject matter hereof.
            </p>
            <h3>2. Composition of Cleanstart Products</h3>
            <p>
              Each Cleanstart product, including without limitation Cleanstart Containers (formerly
              known as Hardened Images or Cleanstart Images), Cleanstart FIPS-validated images, and
              any successor or derivative product offerings (each, a &ldquo;Product&rdquo;), is
              composed of the following:
            </p>
            <ul>
              <li>
                <strong>Cleanstart-authored materials:</strong> hardening configurations, build
                recipes, build pipelines, signing attestations, security advisories, documentation,
                the SBOM (as defined below), the Provenance Attestation (as defined below), and
                other materials authored by Cleanstart.
              </li>
              <li>
                <strong>Third-Party Software:</strong> software components that are not authored by
                Cleanstart, including (i) open source software (&ldquo;OSS&rdquo;) and (ii) where
                applicable, commercial third-party software and integrated services made available
                pursuant to additional licence terms.
              </li>
            </ul>
            <p>
              The composition of each Product is documented in the SBOM made available with that
              Product.
            </p>
            <h3>3. Open Source Software</h3>
            <p>
              <strong>3.1 Definition.</strong> &ldquo;OSS&rdquo; means software licensed under an
              open source licence meeting the definition promulgated by the Open Source Initiative
              (located at https://opensource.org/), or identified as an open source licence by the
              SPDX License List (located at https://spdx.org/licenses/).
            </p>
            <p>
              <strong>3.2 Upstream Licensing.</strong> All OSS components included in Cleanstart
              Products are licensed to Customer by their respective upstream maintainers or
              licensors under the applicable open source licence terms identified in the SBOM made
              available with each Product. Cleanstart does not relicense, sublicense, or modify the
              licence terms of any OSS component included in the Products. Nothing in this Policy,
              the MSA, the SLA, or any related Order Form is intended to limit Customer&apos;s
              rights under, or grant Customer rights that supersede, the terms of any OSS licence.
              Customer&apos;s rights to use, modify, or redistribute any OSS component included in
              a Product are governed solely by the applicable OSS licence and not by the MSA.
            </p>
            <p>
              <strong>3.3 Scope of Cleanstart&apos;s Licence Grant.</strong> The licence granted by
              Cleanstart to Customer under the MSA, and the ownership and intellectual property
              rights asserted by Cleanstart, extend only to the Cleanstart-authored materials
              identified in Section 2 of this Policy. Such licence and rights do not extend to any
              underlying OSS or other Third-Party Software contained within or accessed through the
              Products.
            </p>
            <h3>4. Software Bill of Materials</h3>
            <p>
              <strong>4.1 SBOM Disclosure.</strong> For each Product made generally available,
              Cleanstart publishes a Software Bill of Materials (&ldquo;SBOM&rdquo;) in
              industry-standard formats, including:
            </p>
            <ul>
              <li>
                <strong>Standard SBOM:</strong> SPDX 2.3 format, generated using widely-recognised
                tooling (including syft).
              </li>
              <li>
                <strong>Cleanstart Enhanced SBOM:</strong> SPDX 3.0 format, generated by the
                Cleanstart Enhanced SBOM Generator, providing additional enriched metadata for each
                component.
              </li>
              <li>
                <strong>CycloneDX:</strong> where applicable and as required for specific
                compliance use cases.
              </li>
            </ul>
            <p>
              <strong>4.2 SBOM Contents.</strong> The SBOM identifies, for each component contained
              in the Product, the following information where available: Component name and
              version; Package manager type (for example, apk, deb, rpm, npm, pypi, go); Declared
              licence using SPDX licence identifiers where available; Upstream supplier,
              maintainer, or originator; Upstream source location (repository URL); Cryptographic
              hashes; and Other relevant component metadata.
            </p>
            <p>
              <strong>4.3 SBOM as Authoritative Disclosure.</strong> The SBOM constitutes
              Cleanstart&apos;s complete and authoritative disclosure of the Third-Party Software
              components contained in the applicable Product. Cleanstart&apos;s disclosure
              obligations with respect to such components are satisfied upon making the SBOM
              available to Customer through the Cleanstart Delivery Portal or such other delivery
              mechanism as Cleanstart may designate from time to time.
            </p>
            <p>
              <strong>4.4 SBOM Licensing.</strong> Cleanstart releases each SBOM under the Creative
              Commons CC0 1.0 Universal (Public Domain Dedication) licence, enabling Customer to
              freely use, share, and rely on SBOM data for compliance, security, and operational
              purposes.
            </p>
            <h3>5. Provenance Attestation</h3>
            <p>
              <strong>5.1 Provenance Disclosure.</strong> For each Product made generally available,
              Cleanstart publishes a build provenance attestation (the &ldquo;Provenance
              Attestation&rdquo;) conformant with the Supply chain Levels for Software Artifacts
              (SLSA) framework and the in-toto attestation specification.
            </p>
            <p>
              <strong>5.2 Provenance Contents.</strong> The Provenance Attestation identifies, for
              each Product: The build source repository and the cryptographic commit reference from
              which the Product was built; The build platform and builder identity; The build
              invocation identifier; The cryptographic digest of the resulting Product image; and
              Such additional metadata as required to enable independent verification of build
              integrity and origin.
            </p>
            <p>
              <strong>5.3 Cryptographic Signing.</strong> Cleanstart Products are cryptographically
              signed using industry-standard tooling (including Sigstore Cosign), and Provenance
              Attestations are recorded in tamper-evident transparency logs where applicable,
              enabling Customer to verify the integrity and origin of each Product they deploy.
            </p>
            <h3>6. Commercial Third-Party Components</h3>
            <p>
              Certain Products may include commercial third-party software components, or rely on
              integrated third-party services, that are subject to licence terms, service
              agreements, and policies imposed by their respective owners or licensors
              (&ldquo;Commercial Third-Party Terms&rdquo;). Where applicable, such components and
              the associated Commercial Third-Party Terms are identified in the documentation
              accompanying the affected Product or, where applicable, in an addendum to this
              Policy.
            </p>
            <p>
              Customer must comply with all Commercial Third-Party Terms applicable to the
              components contained in the Products Customer uses, including without limitation
              licensing restrictions, usage limits, data handling requirements, and acceptable use
              obligations. In some cases, Customer may be required to hold a separate, valid
              licence directly from the third-party licensor before Customer is entitled to use the
              affected Product. Where Cleanstart&apos;s or Customer&apos;s licence to any such
              commercial component expires or is terminated for any reason, Cleanstart may suspend
              or terminate Customer&apos;s access to the affected Product, and Cleanstart will use
              commercially reasonable efforts to provide a substantially equivalent Product for the
              remainder of the then-applicable subscription term, where feasible.
            </p>
            <p>
              Cleanstart does not assume liability for a Customer&apos;s failure to comply with any
              Commercial Third-Party Terms.
            </p>
            <h3>7. Customer Responsibilities</h3>
            <p>Customer is responsible for:</p>
            <ul>
              <li>
                Reviewing the SBOM and the applicable Third-Party Software licence terms for each
                Product that Customer uses;
              </li>
              <li>
                Complying with the obligations imposed by such licences, including any attribution,
                notice, or redistribution requirements;
              </li>
              <li>
                Ensuring that Customer&apos;s use, modification, layering, or redistribution of any
                Cleanstart Product does not violate any applicable Third-Party Software licence;
              </li>
              <li>
                Complying with any Commercial Third-Party Terms applicable to the components within
                the Products Customer uses, including obtaining any separate third-party licences
                required for Customer&apos;s use; and
              </li>
              <li>
                Verifying the Provenance Attestation for any Product where Customer requires
                cryptographic assurance of Product origin or integrity prior to deployment.
              </li>
            </ul>
            <h3>8. Cleanstart&apos;s Role</h3>
            <p>
              Cleanstart curates, hardens, and packages Third-Party Software and Cleanstart-authored
              materials into the Products, signs each Product release, and publishes the
              accompanying SBOM and Provenance Attestation. Cleanstart does not modify upstream
              source code in ways that change the licence terms of any OSS component.
            </p>
            <h3>9. Limitation of Liability and Disclaimer</h3>
            <p>
              Cleanstart disclaims responsibility for interruptions, failures, vulnerabilities,
              defects, or deficiencies originating solely from Third-Party Software or from
              integrated third-party services beyond Cleanstart&apos;s reasonable control. Remedies
              and service credits provided under the SLA do not extend to outages or defects caused
              by such Third-Party Software or services, except as expressly stated in the SLA.
              Cleanstart&apos;s obligations and liabilities under this Policy are further limited
              by, and subject to, the warranty disclaimers, exclusions of damages, and Limitations
              of Liability set forth in the MSA, all of which apply in full to any claim arising
              under or in connection with this Policy. Cleanstart makes no warranty, representation,
              or guarantee regarding the accuracy, completeness, or fitness for any particular
              purpose of any Third-Party Software, OSS, or commercial third-party component
              included in or accessed through the Products, except to the extent expressly set
              forth in the MSA.
            </p>
            <h3>10. Updates to this Policy</h3>
            <p>
              Cleanstart may update this Policy from time to time, provided that no such update
              shall materially and adversely diminish Customer&apos;s rights under the then-current
              Order Form for the remainder of its subscription term. The current version of this
              Policy is published at https://www.cleanstart.com/legal. Customer is encouraged to
              review this Policy periodically to remain familiar with its current terms.
            </p>
            <h3>11. Contact</h3>
            <p>
              Questions regarding this Policy, the SBOM, or the Provenance Attestation may be
              directed to Cleanstart&apos;s security and legal teams through the Cleanstart Delivery
              Portal or via the contact mechanisms published at
              <a href="/contact-us">https://www.cleanstart.com/contact-us</a>.
            </p>
`,
  },
  {
    title: "Customer Data Processing Addendum",
    slug: "customer-data-processing-addendum",
    order: 2,
    icon: "FileLock2",
    effectiveDate: "2026-06-04",
    html: `
<p><em>(&ldquo;DPA&rdquo;)</em></p>
            <h2>Purpose</h2>
            <p>
              This Data Processing Addendum (&ldquo;Addendum&rdquo;) forms part of the Master
              Services Agreement and governs CleanStart&apos;s processing of Customer Data in
              connection with the provision of its products and services. The purpose of this
              Addendum is to ensure that such processing is conducted in accordance with applicable
              data protection laws and to establish the respective rights and obligations of the
              parties.
            </p>
            <h2>Definitions</h2>
            <p>
              For the purposes of this Addendum, &ldquo;Customer Data&rdquo; means any personal data
              or other information provided, stored, or transmitted by the Customer or its end-users
              through the use of CleanStart products and services. &ldquo;Processing&rdquo; shall
              have the meaning given under applicable data protection laws, including the General
              Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA), to
              the extent applicable.
            </p>
            <h2>Roles of the Parties</h2>
            <p>
              The Customer acts as the &ldquo;Data Controller&rdquo; (or equivalent under applicable
              law), determining the purposes and means of processing Customer Data. CleanStart acts
              as the &ldquo;Data Processor&rdquo; and processes Customer Data solely on behalf of and
              in accordance with the documented instructions of the Customer, except where otherwise
              required by applicable law.
            </p>
            <h2>Processing Obligations</h2>
            <p>
              CleanStart shall process Customer Data only for the purpose of delivering services
              under the Master Services Agreement, including vulnerability management, remediation,
              image support, and related obligations set forth in the Service Level Agreement.
              CleanStart shall not process Customer Data for its own commercial purposes and shall
              not sell Customer Data to third parties.
            </p>
            <h2>Security and Confidentiality</h2>
            <p>
              CleanStart will implement and maintain appropriate technical and organizational
              measures designed to protect Customer Data against unauthorized access, disclosure,
              alteration, or destruction. These measures include, but are not limited to, encryption,
              access controls, audit logging, vulnerability management, and incident response
              procedures consistent with the security commitments already detailed in the SLA.
              CleanStart personnel are bound by confidentiality obligations and are permitted to
              process Customer Data only as required to perform their duties.
            </p>
            <h2>Subprocessors</h2>
            <p>
              CleanStart may engage third-party subprocessors to support the provision of its
              services, provided that such subprocessors are bound by data protection obligations no
              less protective than those set forth in this Addendum. CleanStart shall maintain a
              current list of subprocessors and will provide customers with notice of any material
              changes. Customers may object to a new subprocessor where they have reasonable grounds
              to believe such engagement would pose an unacceptable risk to data protection.
            </p>
            <h2>International Transfers</h2>
            <p>
              Where the processing of Customer Data involves transfers outside of the jurisdiction in
              which the data originated, CleanStart will ensure that appropriate safeguards are in
              place, such as reliance on Standard Contractual Clauses, binding corporate rules, or
              other lawful transfer mechanisms recognized under applicable law.
            </p>
            <h2>Customer Responsibilities</h2>
            <p>
              The Customer remains responsible for ensuring that its instructions to CleanStart
              comply with applicable data protection laws and for providing legally sufficient
              notices and obtaining necessary consents from its data subjects. The Customer is also
              responsible for the security of its own networks and systems used to transmit Customer
              Data to CleanStart.
            </p>
            <h2>Audit Rights</h2>
            <p>
              Upon reasonable notice, and subject to confidentiality obligations, CleanStart will
              make available to the Customer relevant documentation and information necessary to
              demonstrate compliance with this Addendum. Where required by applicable law, the
              Customer may conduct audits, either directly or through a mutually agreed independent
              auditor, provided that such audits do not unreasonably interfere with CleanStart&apos;s
              business operations.
            </p>
            <h2>Data Subject Rights and Assistance</h2>
            <p>
              CleanStart will provide reasonable assistance to the Customer in responding to requests
              from data subjects, such as requests for access, correction, or deletion of personal
              data, where such assistance is legally required and technically feasible.
            </p>
            <h2>Data Breach Notification</h2>
            <p>
              In the event of a confirmed data breach involving Customer Data, CleanStart will notify
              the Customer without undue delay, providing sufficient details to enable the Customer to
              comply with its legal obligations, including regulatory or data subject notification
              requirements. CleanStart will cooperate with the Customer in investigating, mitigating,
              and remediating the breach.
            </p>
            <h2>Termination and Deletion</h2>
            <p>
              Upon termination or expiration of the Master Services Agreement, CleanStart will, at
              the Customer&apos;s election, return or securely delete all Customer Data, except where
              retention is required by applicable law.
            </p>
            <h2>Governing Law and Hierarchy</h2>
            <p>
              This Addendum shall be governed by the same law and dispute resolution provisions as
              the Master Services Agreement. In the event of conflict between this Addendum and other
              terms of the Agreement, this Addendum shall control with respect to the processing of
              Customer Data.
            </p>
`,
  },
  {
    title: "Limited Use Agreement",
    slug: "limited-use-agreement",
    order: 3,
    icon: "ScrollText",
    effectiveDate: "2026-06-04",
    html: `
<p>
              Triam Security India Pvt. Ltd. (Brand Name: CleanStart)
              <br>
              Effective Date: [&bull;]
            </p>
            <p>
              This Limited Use Agreement (&ldquo;Agreement&rdquo;) governs your access to and use of
              the website www.cleanstart.com (&ldquo;Website&rdquo;) operated by Triam Security India
              Pvt. Ltd., operating under its brand name &ldquo;CleanStart&rdquo; (&ldquo;CleanStart,
              &rdquo; &ldquo;we,&rdquo; or &ldquo;our&rdquo;).
            </p>
            <p>
              By accessing or using this Website, you (&ldquo;User&rdquo; or &ldquo;you&rdquo;) agree
              to be bound by these Terms. If you do not agree, you must not access or use the Website.
            </p>
            <p>
              PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING ANY SERVICE OR SOFTWARE
              OFFERED BY TRIAM SECURITY INDIA PVT. LTD. (operating under its brand name
              &ldquo;CleanStart&rdquo;). BY ACCESSING OR USING THE SERVICES OR SOFTWARE IN ANY MANNER,
              YOU (&ldquo;YOU&rdquo; OR &ldquo;CUSTOMER&rdquo;) AGREE TO BE BOUND BY THESE TERMS (THE
              &ldquo;AGREEMENT&rdquo;) TO THE EXCLUSION OF ALL OTHER TERMS, UNLESS OTHERWISE SPECIFIED
              HEREIN. YOU REPRESENT AND WARRANT THAT YOU HAVE THE AUTHORITY TO ENTER INTO THIS
              AGREEMENT. IF YOU ARE ENTERING INTO THIS AGREEMENT ON BEHALF OF AN ORGANIZATION OR
              ENTITY, REFERENCES TO &ldquo;CUSTOMER&rdquo; AND &ldquo;YOU&rdquo; IN THIS AGREEMENT,
              EXCEPT THIS SENTENCE, REFER TO THAT ORGANIZATION OR ENTITY. IF YOU DO NOT AGREE TO ALL
              OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER. IF THE TERMS OF
              THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS.
            </p>
            <h2>1. Terms Applicable to the Registry and Acceptable Use Policy</h2>
            <h3>1.1 Registry</h3>
            <p>
              To the extent you access or make use of the CleanStart repository available at the
              following URL: [Insert Link] (the &ldquo;Registry&rdquo;), you agree to the terms and
              conditions set forth herein. You are responsible for management of login information and
              access credentials, and must prevent unauthorized access or use of the Registry. You are
              responsible for use by any person to whom you grant access, even if unauthorized.
            </p>
            <p>
              Any content uploaded to the Registry by you is considered Customer Data, for which you
              are solely responsible. You acknowledge that unauthorized third parties may gain access
              to or tamper with Customer Data. CleanStart is not liable for such unauthorized access
              unless caused by CleanStart&apos;s gross negligence or wilful misconduct.
            </p>
            <p>
              Use of the Registry is permitted solely for the Authorized Use defined herein.
            </p>
            <h2>2. Limited Use Terms</h2>
            <p>
              Your use of the Registry, Software, and Service is limited to your internal use in India
              for the period authorized by CleanStart (the &ldquo;Authorized Use&rdquo;).
            </p>
            <h2>3. Terms Applicable to the Service</h2>
            <h3>3.1 Access to and Scope of Service</h3>
            <p>
              CleanStart will use commercially reasonable efforts to provide the service made
              available under this Agreement (the &ldquo;Service&rdquo;). Subject to your compliance,
              you may access and use the Service for the Authorized Use.
            </p>
            <h3>3.2 Restrictions</h3>
            <p>You agree not to, and shall not permit others to:</p>
            <ul>
              <li>(a) remove proprietary notices;</li>
              <li>
                (b) reverse engineer or attempt to discover the Service&apos;s underlying source code
                or algorithms;
              </li>
              <li>(c) rent, resell, or provide access to third parties; or</li>
              <li>(d) use the Service to develop or offer competing products.</li>
            </ul>
            <p>
              Any violation entitles CleanStart to suspend or terminate access immediately without
              liability.
            </p>
            <h3>3.3 Customer Data</h3>
            <p>
              You are solely responsible for Customer Data, including compliance with all Indian laws
              (including the Information Technology Act, 2000 and the Digital Personal Data Protection
              Act, 2023). CleanStart is not responsible for unauthorized access unless due to its
              gross negligence or wilful misconduct.
            </p>
            <h3>3.4 Use of Customer Data</h3>
            <p>
              You grant CleanStart a limited license to use Customer Data solely to provide the
              Service. CleanStart has no obligation to retain Customer Data beyond thirty (30) days
              after termination unless required by law or agreed in writing.
            </p>
            <h3>3.5 Aggregated De-identified Data</h3>
            <p>
              CleanStart may freely use Aggregated De-identified Data for business purposes including
              improving, testing, operating, and marketing its services.
            </p>
            <h3>3.6 Personal Data</h3>
            <p>
              If you use the Service with personal data subject to GDPR or Indian DPDP Act, such use
              is permitted only if you first enter into CleanStart&apos;s Data Processing Agreement
              (&ldquo;DPA&rdquo;).
            </p>
            <h3>3.7 Service Suspension</h3>
            <p>CleanStart may suspend your access:</p>
            <ul>
              <li>(a) if use poses a security risk;</li>
              <li>(b) if you are insolvent or subject to insolvency proceedings; or</li>
              <li>
                (c) following ten (10) days&apos; notice if you breach this Agreement.
              </li>
            </ul>
            <h2>4. Terms Applicable to the CleanStart Software</h2>
            <h3>4.1 License Grant</h3>
            <p>
              CleanStart grants you a term-limited, non-exclusive, non-transferable, non-assignable
              and non-sublicensable license to use CleanStart software (&ldquo;Software&rdquo;) solely
              for the Authorized Use.
            </p>
            <h3>4.2 License Limitations</h3>
            <p>You shall not:</p>
            <ul>
              <li>(a) exceed the license scope;</li>
              <li>(b) make copies or distribute the Software;</li>
              <li>(c) sublicense, rent, or transfer rights;</li>
              <li>(d) reverse engineer, except as permitted by Indian law;</li>
              <li>(e) modify or create derivative works;</li>
              <li>(f) remove intellectual property notices;</li>
              <li>
                (g) use the Software with open-source licenses that require distribution in source
                code;
              </li>
              <li>(h) use the Software for competing products; or</li>
              <li>(i) misuse CleanStart&apos;s trademarks or brand.</li>
            </ul>
            <p>
              Unauthorized use may constitute a cognizable offence under Indian law.
            </p>
            <h2>5. Termination</h2>
            <h3>5.1 Term</h3>
            <p>
              The term of this Agreement shall commence on the date You first download the Software or
              access the Service (the &ldquo;Effective Date&rdquo;), and unless terminated earlier
              according to this Section 5, will terminate at the end of the Authorized Use (the
              &ldquo;Term&rdquo;).
            </p>
            <h3>5.2 Termination</h3>
            <p>This Agreement may be terminated:</p>
            <ul>
              <li>
                (a) by either Party for uncured material breach within ten (10) days of written
                notice of such breach to the other party if the breach is remediable, or immediately
                upon notice if the breach is not remediable; or
              </li>
              <li>
                (b) by CleanStart at any time, with or without cause, by notice or by suspending
                access.
              </li>
            </ul>
            <h3>5.3 Effect of Termination</h3>
            <p>
              Upon termination, you must immediately cease use of the Registry, Service, and Software.
              CleanStart is not obligated to return Customer Data unless legally required and
              expressly requested within 15 days.
            </p>
            <h3>5.4 Survival</h3>
            <p>
              The following provisions will survive termination of this Agreement: Sections 3.4 (Use
              of Customer Data), 3.5 (Aggregated De-Identified Data), 5.3 (Effect of Termination),
              Section 5.4 (Survival), Section 6 (Confidentiality and Ownership), Section 9 (Limitation
              of Liability), Section 10 (Miscellaneous).
            </p>
            <h2>6. Confidentiality and Ownership</h2>
            <h3>6.1 Confidentiality</h3>
            <p>
              During the term of this Agreement, either party may provide the other party with
              confidential and/or proprietary materials and information (&ldquo;Confidential
              Information&rdquo;). All materials and information provided by the disclosing party and
              identified at the time of disclosure as &ldquo;Confidential&rdquo; or bearing a similar
              legend, and all other information that the receiving party reasonably should have known
              was the Confidential Information of the disclosing party, shall be considered
              Confidential Information. This Agreement is Confidential Information, and all pricing
              terms are CleanStart Confidential Information. The receiving party shall maintain the
              confidentiality of the Confidential Information and will not disclose such information to
              any third party without the prior written consent of the disclosing party. The
              receiving party will only use the Confidential Information internally for the purposes
              contemplated hereunder. The obligations in this Section shall not apply to any
              information that: (a) is made generally available to the public without breach of this
              Agreement, (b) is developed by the receiving party independently from and without
              reference to the Confidential Information, (c) is disclosed to the receiving party by a
              third party without restriction, or (d) was in the receiving party&apos;s lawful
              possession prior to the disclosure and was not obtained by the receiving party either
              directly or indirectly from the disclosing party. The receiving party may disclose
              Confidential Information as required by law or court order provided that the receiving
              party provides the disclosing party with prompt written notice thereof and uses the
              receiving party&apos;s best efforts to limit disclosure. At any time, upon the
              disclosing party&apos;s written request, the receiving party shall return to the
              disclosing party all of the disclosing party&apos;s Confidential Information in its
              possession, including, without limitation, all copies and extracts thereof.
            </p>
            <h3>6.2 Ownership</h3>
            <p>
              CleanStart retains all right, title, and interest in and to the Registry, Service,
              Software, and any software, products, works or other intellectual property created,
              used, provided or made available by CleanStart under or in connection with the Registry,
              Service or Software.
            </p>
            <h3>6.3 Feedback</h3>
            <p>
              Customer may from time to time provide suggestions, comments or other feedback to
              CleanStart with respect to the Registry, Service or Software (&ldquo;Feedback&rdquo;).
              Feedback, even if designated as confidential by Customer, shall not create any
              confidentiality obligation for CleanStart notwithstanding anything else. Customer shall,
              and hereby does, grant to CleanStart a non-exclusive, worldwide, perpetual, irrevocable,
              transferable, sublicensable, royalty-free, fully paid-up license to use and exploit the
              Feedback for any purpose. Nothing in this Agreement will impair CleanStart&apos;s right
              to develop, acquire, license, market, promote or distribute products, services, software
              or technologies that perform the same or similar functions as, or otherwise compete
              with, any products, software or technologies that Customer may develop, produce, market,
              or distribute.
            </p>
            <h2>7. Indemnification</h2>
            <p>
              Customer shall indemnify, defend, and hold harmless CleanStart, its affiliates, and
              representatives, and each of their respective officers, directors, employees and
              representatives from and against any claims, damages, losses, liabilities, costs, and
              expenses (including reasonable attorneys&apos; fees), or governmental proceedings
              (including under Indian IT and data protection laws) arising out of or relating to any
              third party claim with respect to:
            </p>
            <ul>
              <li>(a) Customer Data;</li>
              <li>
                (b) breach of this Agreement or violation of applicable law by Customer;
              </li>
              <li>
                (c) alleged infringement or misappropriation of third-party intellectual property
                rights resulting from Customer Data; or
              </li>
              <li>(d) breach of, or non-compliance with, the AUP.</li>
            </ul>
            <h2>8. Warranty Disclaimer</h2>
            <p>
              CleanStart does not represent or warrant that the operation of the Registry, Service or
              Software (or any portion thereof) will be uninterrupted or error free, or that the
              Registry, Service or Software (or any portion thereof) will operate in combination with
              other hardware, software, systems or data not provided by CleanStart. CUSTOMER
              ACKNOWLEDGES THAT CLEANSTART MAKES NO EXPRESS OR IMPLIED REPRESENTATIONS OR WARRANTIES
              OF ANY KIND WITH RESPECT TO THE REGISTRY, SERVICE OR SOFTWARE, OR THEIR CONDITION.
              CLEANSTART HEREBY EXPRESSLY EXCLUDES ANY AND ALL OTHER EXPRESS OR IMPLIED
              REPRESENTATIONS OR WARRANTIES, WHETHER UNDER COMMON LAW, STATUTE OR OTHERWISE, INCLUDING
              WITHOUT LIMITATION ANY AND ALL WARRANTIES AS TO MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, SATISFACTORY QUALITY OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS.
            </p>
            <h2>9. Limitation of Liability</h2>
            <p>
              IN NO EVENT SHALL CLEANSTART BE LIABLE FOR ANY LOST DATA, LOST PROFITS, BUSINESS
              INTERRUPTION, REPLACEMENT SERVICE OR OTHER SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE
              OR INDIRECT DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THEORY OF LIABILITY.
              CLEANSTART&apos;S LIABILITY FOR ALL CLAIMS ARISING UNDER THIS AGREEMENT, WHETHER IN
              CONTRACT, TORT OR OTHERWISE, SHALL NOT EXCEED THE LESSER OF (A) THE FEES PAID BY CUSTOMER
              IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM; OR (B) ONE LAKH (INR 1,00,000).
            </p>
            <h2>10. Miscellaneous</h2>
            <h3>10.1 Export Control</h3>
            <p>
              Customer shall comply with Indian and applicable export/import control laws.
            </p>
            <h3>10.2 Compliance with Laws</h3>
            <p>
              Customer shall comply with all applicable Indian laws including the IT Act 2000, DPDP
              Act 2023, and privacy regulations.
            </p>
            <p>
              Customer shall comply with all applicable laws and regulations in its use of the
              Registry and any Software or Service, including without limitation the unlawful
              gathering or collecting, or assisting in the gathering or collecting of information in
              violation of any privacy laws or regulations. Customer shall, at its own expense,
              defend, indemnify and hold harmless CleanStart from and against any and all claims,
              losses, liabilities, damages, judgments, government or federal sanctions, costs and
              expenses (including attorneys&apos; fees) incurred by CleanStart arising from any claim
              or assertion by any third party of violation of privacy laws or regulations by Customer
              or any of its agents, officers, directors or employees.
            </p>
            <h3>10.3 Assignment</h3>
            <p>
              Neither party may transfer or assign its rights and obligations under this Agreement
              without the prior written consent of the other party. Notwithstanding the foregoing,
              CleanStart may transfer and assign its rights under this Agreement without consent from
              the other party in connection with a change in control, acquisition or sale of all or
              substantially all of its assets. Any attempted assignment in violation of the foregoing
              shall be null and void.
            </p>
            <h3>10.4 Force Majeure</h3>
            <p>
              Neither party shall be responsible for failure or delay in performance by events out of
              their reasonable control, including but not limited to, acts of God, Internet outage,
              terrorism, war, fires, earthquakes and other disasters (each a &ldquo;Force
              Majeure&rdquo;).
            </p>
            <h3>10.5 Notices</h3>
            <p>
              Notices must be in writing and delivered by courier, registered post, or recognized
              delivery service.
            </p>
            <h3>10.6 No Agency</h3>
            <p>
              Both parties agree that no agency, partnership, joint venture, or employment is created
              as a result of this Agreement. Customer does not have any authority of any kind to bind
              CleanStart.
            </p>
            <h3>10.7 Governing Law and Jurisdiction</h3>
            <p>
              This Agreement shall be governed by and construed in accordance with the laws of India.
              Any disputes shall be subject to the exclusive jurisdiction of the courts at [Insert
              City - e.g., New Delhi or Gurugram], India.
            </p>
            <h3>10.8 Publicity</h3>
            <p>
              Customer hereby grants CleanStart the right to identify Customer as a CleanStart
              customer, and use Customer&apos;s name, mark and logo on CleanStart&apos;s website and
              in CleanStart&apos;s marketing materials with respect to the same without royalty or
              compensation.
            </p>
            <h3>10.9 Updated Agreement</h3>
            <p>
              CleanStart reserves the right to update this Agreement at any time. The terms and
              conditions of the updated version of the Agreement shall apply to the Registry, Services
              and Software following the date of publication of the updated version on
              CleanStart&apos;s website at the following URL: [www.cleanstart.com]. If Customer does
              not agree with any terms of the updated Agreement, Customer may not use or access the
              Registry, Service or Software in any manner.
            </p>
            <h3>10.10 Contact Information</h3>
            <p>
              Triam Security India Pvt. Ltd. (Brand Name: CleanStart)
              <br>
              [Registered Office Address]
              <br>
              Email: <a href="mailto:legal@cleanstart.com">legal@cleanstart.com</a>
            </p>
            <h3>10.11 Entire Agreement</h3>
            <p>
              This Agreement is the complete and exclusive statement of the mutual understanding of
              the parties and supersedes and cancels all previous written and oral agreements,
              communications, and other understandings relating to the subject matter of this
              Agreement, and all waivers and modifications must be in a writing signed by both
              parties, except as otherwise provided in this Agreement. Any term or provision of this
              Agreement held to be illegal or unenforceable shall be, to the fullest extent possible,
              interpreted so as to be construed as valid, but in any event the validity or
              enforceability of the remainder hereof shall not be affected.
            </p>
`,
  },
  {
    title: "Policies and Commitments",
    slug: "policies-and-commitments",
    order: 4,
    icon: "BadgeCheck",
    effectiveDate: "2026-06-04",
    html: `
<p>
              <em>(including Security Commitments and Service Level Agreements)</em>
            </p>
            <h2>Purpose</h2>
            <p>
              This Policy consolidates CleanStart&apos;s key commitments regarding the security,
              availability, and reliability of its products and services. It supplements the Master
              Services Agreement and forms the foundation of CleanStart&apos;s contractual obligations
              to its customers, alongside the Service Level Agreement (&ldquo;SLA&rdquo;) and related
              supporting documents.
            </p>
            <h2>Security Commitments</h2>
            <p>
              CleanStart is committed to maintaining the confidentiality, integrity, and availability
              of customer data and to implementing industry-standard security practices across its
              operations. Security measures include continuous vulnerability scanning, patch
              management, access controls, encryption of data at rest and in transit, and incident
              response protocols. These commitments are reinforced by the Vulnerability Management and
              Remediation SLA, which defines strict timelines for addressing vulnerabilities
              classified under the Common Vulnerability Scoring System (CVSS).
            </p>
            <h2>Availability and Performance Commitments</h2>
            <p>
              CleanStart guarantees high levels of availability for its image registry and related
              services, with commitments of 99.9% uptime for registry services and 99.95% uptime for
              image pull availability, measured monthly. In addition, CleanStart ensures timely
              support response based on priority levels, ranging from a two-hour response time for
              critical issues to an eight-business-hour response for medium or low-priority issues.
            </p>
            <h2>Transparency and Reporting</h2>
            <p>
              CleanStart provides ongoing transparency into its security posture and service
              performance. Customers receive monthly vulnerability reports, proactive notifications of
              critical and high-severity issues, and access to a public security dashboard that
              displays current vulnerability status for generally available images. CleanStart also
              commits to documenting any exceptions or exclusions to remediation and reviewing its
              security posture annually to incorporate industry best practices.
            </p>
            <h2>Customer Responsibilities</h2>
            <p>
              CleanStart&apos;s ability to deliver on these commitments depends on the active
              cooperation of its customers. Customers are responsible for submitting accurate and
              complete support requests, designating primary points of contact, and responding
              promptly to CleanStart&apos;s security communications. Customers must also ensure that
              their use of CleanStart products complies with applicable laws and third-party terms,
              and that their own networks and environments are secured against vulnerabilities outside
              CleanStart&apos;s control.
            </p>
            <h2>Service Credits and Remedies</h2>
            <p>
              In the event that CleanStart fails to meet its defined SLA obligations, customers may be
              entitled to service credits as set forth in the SLA. These credits serve as the sole and
              exclusive remedy for SLA breaches, ensuring accountability while providing customers with
              meaningful compensation where commitments are not met.
            </p>
            <h2>Continuous Improvement</h2>
            <p>
              CleanStart is dedicated to continuous improvement of its policies, security practices,
              and commitments. Security measures, remediation processes, and service standards are
              reviewed annually and updated to reflect customer feedback, regulatory developments, and
              advancements in industry best practices.
            </p>
`,
  },
  {
    title: "Pre-General Availability Terms",
    slug: "pre-general-availability-terms",
    order: 5,
    icon: "FileCheck2",
    effectiveDate: "2026-06-04",
    html: `
<h2>Purpose</h2>
            <p>
              These Pre-GA Terms apply to CleanStart&trade; products, features, or services that are
              designated as alpha, beta, preview, or otherwise not yet generally available
              (&ldquo;Pre-GA Offerings&rdquo;). They supplement the Master Services Agreement and
              related Service Level Agreements, and govern the Customer&apos;s use of Pre-GA Offerings
              provided by CleanStart.
            </p>
            <h2>Limited Availability and Functionality</h2>
            <p>
              Pre-GA Offerings are made available at CleanStart&apos;s sole discretion for evaluation,
              testing, and feedback purposes only. They may be incomplete, may contain errors or
              defects, and may not function in the same manner as generally available products.
              CleanStart does not guarantee continued availability of any Pre-GA Offering and may
              modify, suspend, or discontinue such offerings at any time without notice.
            </p>
            <h2>Exclusions from SLA and Warranties</h2>
            <p>
              Unless expressly stated otherwise, Pre-GA Offerings are provided &ldquo;as is&rdquo; and
              are excluded from the commitments, service credits, and remedies specified under the
              CleanStart Service Level Agreement. CleanStart disclaims all warranties with respect to
              Pre-GA Offerings, whether express, implied, or statutory, including warranties of
              performance, reliability, or fitness for a particular purpose.
            </p>
            <h2>Customer Responsibilities</h2>
            <p>
              Customers using Pre-GA Offerings acknowledge that such use is at their sole risk and
              agree to use them only for non-production purposes, unless expressly authorized by
              CleanStart. Customers must provide prompt feedback on issues, performance, and
              usability, and consent to CleanStart&apos;s use of such feedback for product improvement
              without restriction. Customers are further responsible for ensuring that their test use
              of Pre-GA Offerings does not expose confidential or sensitive data without appropriate
              safeguards.
            </p>
            <h2>Data Handling and Security</h2>
            <p>
              While CleanStart applies commercially reasonable security measures across its services,
              Customers acknowledge that Pre-GA Offerings may not have undergone the same level of
              security review, certification, or compliance validation as generally available
              services. Accordingly, Customers are advised not to rely on Pre-GA Offerings for
              mission-critical workloads or for processing highly sensitive data.
            </p>
            <h2>Transition to General Availability</h2>
            <p>
              CleanStart has no obligation to release any Pre-GA Offering as a generally available
              product. If a Pre-GA Offering transitions to general availability, continued use shall
              be subject to the standard terms of the Master Services Agreement and SLA, and may
              require execution of additional orders or amendments.
            </p>
            <h2>Termination</h2>
            <p>
              Either party may terminate participation in a Pre-GA Offering at any time upon written
              notice. Upon termination, Customer must cease all use of the Pre-GA Offering and, if
              applicable, return or delete any related materials in accordance with CleanStart&apos;s
              instructions.
            </p>
            <h2>Governing Law</h2>
            <p>
              These Pre-GA Terms shall be governed by the same law and dispute resolution provisions
              as the Master Services Agreement.
            </p>
`,
  },
  {
    title: "Trademark Usage Policy",
    slug: "trademark-usage-policy",
    order: 6,
    icon: "Stamp",
    effectiveDate: "2026-06-04",
    html: `
<p><em>(Logo, Copy, and Images)</em></p>
            <h2>Purpose</h2>
            <p>
              This Policy sets out the rules governing the use of CleanStart&trade; trademarks,
              service marks, logos, product names, images, and related brand assets
              (&ldquo;Marks&rdquo;). Its objective is to ensure the integrity of the CleanStart brand
              is preserved, while allowing authorized customers, partners, and third parties to make
              accurate and appropriate references to CleanStart products and services.
            </p>
            <h2>Ownership</h2>
            <p>
              All rights, title, and interest in the Marks remain the exclusive property of
              CleanStart. No transfer of ownership or implied license is granted under this Policy.
              Permission to use the Marks is strictly limited to the conditions described herein.
            </p>
            <h2>Authorized Usage</h2>
            <p>
              CleanStart permits use of its Marks solely for the purposes of identifying genuine
              CleanStart products or services, or to indicate a bona fide customer or partnership
              relationship, provided such use is accurate and not misleading. Marks must always appear
              in the exact form supplied by CleanStart, without modification, and must comply with any
              applicable brand guidelines issued by the company.
            </p>
            <h2>Restrictions on Use</h2>
            <p>
              Marks may not be altered, distorted, or combined with any other logos, words, or
              graphics. They may not be used in a manner that implies endorsement, sponsorship, or
              affiliation beyond what has been expressly authorized in writing. CleanStart Marks must
              not be incorporated into product names, business names, domain names, advertising
              keywords, or social media handles. Use of screenshots, product images, or documentation
              excerpts must remain contextual, factual, and non-misleading.
            </p>
            <h2>Presentation Standards</h2>
            <p>
              When displaying the CleanStart logo, appropriate clear space and proportional scaling
              must be maintained, and the logo must not be obscured, cropped, or placed on a
              background that impairs its legibility. References to CleanStart products should use the
              full and proper product names as they appear in official documentation, including the
              required &trade; or &reg; symbol at least once per page, document, or webpage. An
              appropriate attribution statement must accompany such use, for example:
              &ldquo;CleanStart&trade; is a registered trademark of CleanStart, Inc. All rights
              reserved.&rdquo;
            </p>
            <h2>Use of Images and Documentation</h2>
            <p>
              Official images, diagrams, and excerpts from CleanStart materials may be reproduced only
              for non-commercial, educational, or informational purposes, provided that the content is
              not altered and the source is clearly acknowledged. Any commercial use, including use in
              promotional or marketing materials, requires prior written authorization from
              CleanStart.
            </p>
            <h2>Enforcement</h2>
            <p>
              Unauthorized use of Marks constitutes a violation of CleanStart&apos;s intellectual
              property rights and may result in revocation of any usage rights, termination of related
              agreements, or pursuit of legal remedies. CleanStart reserves the right to amend this
              Policy at any time to reflect changes in its branding strategy, business operations, or
              applicable law.
            </p>
`,
  },
  {
    title: "Vulnerability Disclosure Policies",
    slug: "vulnerability-disclosure-policies",
    order: 7,
    icon: "Bug",
    effectiveDate: "2026-06-04",
    html: `
<p><em>(Inbound &amp; Outbound)</em></p>
            <h2>1. Purpose</h2>
            <p>
              This Policy establishes CleanStart&apos;s process for the responsible disclosure,
              receipt, and handling of security vulnerabilities, whether reported by external parties
              (Inbound) or disclosed by CleanStart to customers and the public (Outbound). The aim is
              to promote transparency, minimize security risks, and align with CleanStart&apos;s
              Service Level Agreements on vulnerability management.
            </p>
            <h2>2. Inbound Vulnerability Disclosure (External Reports)</h2>
            <ul>
              <li>
                <strong>Reporting Channels:</strong> Security researchers, customers, and third
                parties may submit vulnerability reports via the official CleanStart security portal
                (<a href="mailto:security@cleanstart.com">security@cleanstart.com</a>) or via the
                CleanStart Vulnerability Disclosure Program page.
              </li>
              <li>
                <strong>Safe Harbor:</strong> CleanStart will not pursue legal action against
                good-faith researchers who follow this Policy and do not exploit vulnerabilities
                beyond what is necessary to demonstrate proof-of-concept.
              </li>
              <li>
                <strong>Required Information:</strong>
                <ul>
                  <li>
                    Description of the issue, including affected product/version
                  </li>
                  <li>Steps to reproduce</li>
                  <li>Potential impact assessment (if known)</li>
                </ul>
              </li>
              <li>
                <strong>Acknowledgement:</strong> CleanStart will acknowledge valid reports within
                <strong>48 hours</strong> and provide regular updates until resolution.
              </li>
              <li>
                <strong>Triage &amp; SLA Alignment:</strong> Reported vulnerabilities will be assessed
                under the CVSS-based severity model and addressed in accordance with remediation
                timelines set forth in the SLA.
              </li>
              <li>
                <strong>Researcher Credit:</strong> With consent, CleanStart may credit the reporter
                in release notes or advisories.
              </li>
            </ul>
            <h2>
              3. Outbound Vulnerability Disclosure (CleanStart to Customers / Public)
            </h2>
            <ul>
              <li>
                <strong>Notification Commitment:</strong> CleanStart will notify affected customers of
                Critical and High vulnerabilities within 24 hours of validation and provide
                remediation guidance.
              </li>
              <li>
                <strong>Communication Channels:</strong> Direct customer notifications via registered
                security contacts; public advisories posted on the CleanStart security dashboard and
                mailing list.
              </li>
              <li>
                <strong>Content of Notifications:</strong>
                <ul>
                  <li>Nature of vulnerability and CVSS score</li>
                  <li>Affected products/versions</li>
                  <li>Workarounds or mitigation steps</li>
                  <li>Timeline for patch availability</li>
                </ul>
              </li>
              <li>
                <strong>Major Vulnerability Events:</strong> In cases where vulnerabilities affect a
                significant portion of CleanStart images, notification and remediation steps will
                follow the SLA-defined escalation protocol.
              </li>
            </ul>
            <h2>4. Exclusions</h2>
            <ul>
              <li>
                Reports concerning vulnerabilities in customer code, third-party software not
                maintained by CleanStart, or integrations outside CleanStart&apos;s control.
              </li>
              <li>Submissions lacking sufficient detail to reproduce.</li>
            </ul>
            <h2>5. Continuous Improvement</h2>
            <p>
              This Policy will be reviewed annually to incorporate feedback from customers,
              researchers, and regulatory changes.
            </p>
`,
  },
  {
    title: "Acceptable Use Policy",
    slug: "acceptable-use-policy",
    order: 8,
    icon: "Scale",
    effectiveDate: "2026-06-04",
    html: `
<h2>Introduction</h2>
            <p>
              This Acceptable Use Policy (&quot;AUP&quot;) governs your access to and use of all
              products, services, platform features, container image repositories, APIs,
              dashboards, and documentation (collectively, the &quot;Services&quot;) provided by
              CleanStart Security Inc. (&quot;CleanStart,&quot; &quot;we,&quot; &quot;us,&quot; or
              &quot;our&quot;).
            </p>
            <p>
              By accessing or using the Services, you (&quot;User,&quot; &quot;Customer,&quot; or
              &quot;you&quot;) agree to comply with this AUP. This AUP is incorporated by reference
              into CleanStart&apos;s Terms of Service and any applicable Master Service and License
              Agreement or Order Form executed between you and CleanStart. If you are accepting this
              AUP on behalf of a company or other legal entity, you represent that you have the
              authority to bind that entity.
            </p>
            <p>
              CleanStart reserves the right to modify this AUP at any time. Updates will be posted
              to our website with a revised effective date and are binding upon posting. Continued
              use of the Services constitutes acceptance of the revised AUP.
            </p>
            <h2>Reporting Suspected Violations</h2>
            <p>
              We encourage anyone who suspects a violation of this AUP to report it to us at
              <a href="mailto:legal@cleanstart.com">legal@cleanstart.com</a>. We investigate all
              reports and respond in the way we consider appropriate.
            </p>
            <h2>Permitted Use</h2>
            <p>
              You may use CleanStart&apos;s Services for any lawful purpose that is consistent with
              your agreement with us. You are solely responsible for any data, information, or
              materials you use in connection with CleanStart&apos;s products and services,
              including maintaining your own copies. CleanStart does not monitor your content for
              illegal activity. You must comply with all applicable laws and regulations. Any use
              that facilitates a violation of applicable law is strictly prohibited.
            </p>
            <h2>What You Cannot Do</h2>
            <p>
              You may not use CleanStart&apos;s Services for the following, including but not
              limited to:
            </p>
            <ul>
              <li>
                <strong>Illegal or Harmful Activity</strong> Using the Services for anything that
                violates applicable law, promotes violence or hatred, causes harm to others, or
                damages CleanStart&apos;s reputation.
              </li>
              <li>
                <strong>Objectionable Content</strong> Using the Services to create, share, or
                distribute content that is harassing, defamatory, obscene, indecent, or otherwise
                objectionable.
              </li>
              <li>
                <strong>Fraudulent or Misleading Activity</strong> Using the Services to make false
                representations, spread misleading information, or engage in any deceptive or
                fraudulent conduct.
              </li>
              <li>
                <strong>Intellectual Property Violations</strong> Using the Services in a way that
                infringes the rights of others, including content protected by copyright,
                trademark, or patent.
              </li>
              <li>
                <strong>Impersonation</strong> Using the Services to impersonate CleanStart, its
                team, or any other person or entity, or misrepresenting your affiliation with
                CleanStart.
              </li>
              <li>
                <strong>Unauthorized Redistribution</strong> Reselling, sublicensing, or
                distributing CleanStart&apos;s Services to third parties as a standalone product
                without our prior written consent.
              </li>
              <li>
                <strong>Competitive Use</strong> Using CleanStart&apos;s Services to develop or
                offer products or services that compete with CleanStart.
              </li>
              <li>
                <strong>Disruption</strong> Using the Services in any way that interferes with,
                degrades, or disrupts the experience of other users or the normal operation of
                CleanStart&apos;s platform.
              </li>
              <li>
                <strong>Privacy Violations</strong> Using the Services to collect or misuse
                information about others without their consent or sharing your account access with
                unauthorized parties.
              </li>
            </ul>
            <h2>Compliance with Applicable Laws</h2>
            <p>
              You agree to use the CleanStart Service in full compliance with all applicable local,
              state, national, and international laws and regulations, including but not limited
              to data protection laws, privacy laws, and export control regulations.
            </p>
            <h2>General Terms</h2>
            <p>
              If you breach this AUP, CleanStart reserves the right to immediately suspend or
              terminate your access to the Service. Where possible, we will endeavour to notify you
              and provide an opportunity to remedy the situation before taking further action.
            </p>
            <p>
              CleanStart may also terminate your subscription agreement for cause in the event of a
              serious or repeated violation. We reserve the right to remove any prohibited content
              and deny access to any person who violates this AUP.
            </p>
            <p>
              Please note that CleanStart may be required to disclose information about your use of
              the Service if mandated by law, regulation, court order, or government request.
              Where we are permitted to do so, we will notify you of any such disclosure.
            </p>
`,
  },
  {
    title: "Privacy Policy",
    slug: "privacy-policy",
    order: 9,
    icon: "ShieldCheck",
    effectiveDate: "2026-03-31",
    html: `
<h2>Data Controller / Data Fiduciary</h2>
            <p>
              For the purposes of applicable data protection laws: For users located in India,
              CleanStart Security Private Limited acts as the &ldquo;Data Fiduciary&rdquo;. For
              users located in Singapore, CleanStart Security Pte. Ltd. acts as the data controller.
              For users located in the United States, CleanStart Security INC acts as the data
              controller. For users located outside these jurisdictions, the relevant CleanStart
              group entity providing the Services shall act as the data controller.
            </p>
            <p>
              CleanStart, its affiliates and subsidiaries (&ldquo;we,&rdquo; &ldquo;us,&rdquo;
              &ldquo;our&rdquo;), thank you for using our services. This Privacy Policy aims to
              inform you about the collection, use, and disclosure of personal information when you
              use our website, software, and services, collectively referred to as the
              &ldquo;Service&rdquo;. We are committed to protecting your privacy and ensuring
              compliance with relevant data protection laws in the countries we operate in.
            </p>

            <h2>1. Scope</h2>
            <p>
              At CleanStart, we believe that you should always be aware of the information we
              collect from you, the reasons for which we use it, and be empowered to make informed
              choices regarding the data you share with us. Accordingly, we aim to maintain
              complete transparency by informing you: how and why we collect, store, and process
              your personal data in the course of your interactions with us; the rights available
              to you in controlling and defining the extent of such interactions.
            </p>
            <p><strong>Our Services are not directed at children.</strong></p>
            <p>
              In India, we do not knowingly process personal data of individuals under 18 years of
              age without verifiable parental consent, as required under applicable law. In the
              United States, our Services are not directed at children under 13 years of age. In
              Singapore, we comply with applicable requirements relating to minors&rsquo; data. If
              we become aware that we have collected personal data of a child in violation of
              applicable law, we will take steps to delete such information.
            </p>

            <h2>2. Summary</h2>
            <p>
              While we would strongly advise you to read the Policy in full, the following summary
              will give you a snapshot of the salient points covered herein:
            </p>
            <ul>
              <li>
                This Policy details the critical aspects governing your personal data relationship
                with CleanStart Security INC, having its registered office at 16192 Coastal
                Highway, Lewes, Delaware 19958, United States, and its subsidiary, CleanStart
                Security Private Limited., a company incorporated under the Laws of India, and
                having its registered office at 207-208, Arizona Business, Near Nav Gujarat
                College, Usmanpura, Ashram Road, Ahmedabad Gujarat 380013, India and CleanStart
                Security Pte. Ltd. a company incorporated under the Laws of Singapore, and having
                its registered office at 1003 Bukit Merah Central, #07-23, Singapore 159836
                (collectively, CleanStart);
              </li>
              <li>
                Your personal data relationship with CleanStart varies based on the capacity in
                which you interact with us/avail of our Services. You could be: (i) a visitor to
                <a href="https://www.cleanstart.com/">https://www.cleanstart.com/</a>
                (&ldquo;Website&rdquo;) or any pages thereof (&ldquo;Visitor&rdquo;); (ii) a
                person/entity availing of one of our Services (&ldquo;Customer&rdquo;); or (iii) an
                employee/agent/representative/appointee of a customer who uses the said Service
                (&ldquo;User&rdquo;);
              </li>
              <li>
                Based on whether you are a Visitor, Customer or User, the type of data we collect
                and the purpose for which we use it will differ and this Policy details such
                variations;
              </li>
              <li>
                This Policy is a part of and should be read in conjunction with our
                <a href="/legal">Legal Terms</a>.
              </li>
              <li>
                This Policy will clarify the rights available to you vis-&agrave;-vis the personal
                data you share with us.
              </li>
              <li>
                If you have any queries or concerns with this Policy, please contact our Grievance
                Officer (refer Section 11). If you do not agree with the Policy, we would advise
                you to not visit/use the Website or the CleanStart application(s)/platform(s)
                (collectively &ldquo;App&rdquo;).
              </li>
            </ul>

            <h2>3. Information We Collect and How We Use</h2>
            <p>
              You agree to use the CleanStart Service in full compliance with all applicable local,
              state, national, and international laws and regulations, including but not limited to
              data protection laws, privacy laws, and export control regulations.
            </p>
            <table>
              <thead>
                <tr>
                  <th>Type of User</th>
                  <th>What Data We May Collect</th>
                  <th>How and Why We Use It</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>Visitor</strong></td>
                  <td>
                    Your IP Address; Your location; How you behave on the Website (what pages you
                    land on, how much time you spend, etc.); What Device you use to access the
                    Website and its details (model, operating system, etc.); Cookies and Web
                    Beacon data; and Data from third parties who have your explicit consent to
                    lawfully share that data. If you submit an inquiry through the Website, we will
                    ask for your Name and E-mail. Job applicant information as we may post job
                    openings and opportunities on the website. If you reply to one of these
                    postings by submitting your application, we will collect your full name, email
                    address, phone number, resume, and cover letter.
                  </td>
                  <td>
                    We use this information to analyse and identify your behaviour and enhance the
                    interactions you have with the Website. If you submit your details and give us
                    your consent, we may use your data to send you e-mails/newsletters, re-target
                    CleanStart advertisements or re-market our Services using services from
                    third-parties like Facebook and Google.
                  </td>
                </tr>
                <tr>
                  <td><strong>Customer</strong></td>
                  <td>
                    The name and e-mail of your representative who signs up for a Service on your
                    behalf; and Credit Card/Debit Card/Other Payment Mode information to check your
                    financial qualifications, detect fraud and facilitate payments for our
                    Services. Feedback and support information such as information collected based
                    on your participation in our surveys, including feedback on your use of our
                    Services, and any information contained in support requests.
                  </td>
                  <td>
                    We collect this data in order to help you register for and facilitate provision
                    of our Services. We also use this data to enable you to make payments for our
                    Services. We use a third-party service provider to manage payment processing.
                    If you give us your consent, we may send you newsletters and e-mails to market
                    other products and services we may provide.
                  </td>
                </tr>
                <tr>
                  <td><strong>User</strong></td>
                  <td>
                    Your name, e-mail; Your IP Address; Your location (unless you deactivate
                    location services in the relevant section of the App); How you behave in the
                    relevant product environment and use the features; What device you use to
                    access the Website/App and its details (model, operating system, etc.); Cookies
                    and Web Beacon data; Data from third parties who have your explicit consent to
                    lawfully share that data.
                  </td>
                  <td>
                    We collect this data in order to facilitate provision of our Services. We will
                    occasionally send you e-mails regarding changes or updates to the Service that
                    you are using. If you give us your consent, we may send you newsletters and
                    e-mails to market other products and services we may provide. We may also
                    conduct anonymized usage behaviour analysis at the aggregate level to determine
                    how the features of a particular Service are being used.
                  </td>
                </tr>
              </tbody>
            </table>
            <h3>Information We Collect from External Sources</h3>
            <p>
              We may occasionally receive additional information about you from external sources,
              including third parties from whom we have lawfully acquired personal data. Such
              sources may include joint marketing collaborators, our group entities or affiliates,
              lead generation partners, event organisers, public databases, credit verification
              agencies, data service providers, and social media platforms. The categories of
              personal information obtained from such external sources may consist of: Contact and
              professional details such as mailing addresses, designations, email addresses, phone
              numbers, intent or behavioural insights, IP addresses, social media accounts,
              LinkedIn profiles, and other customised profile data. Information contained in
              r&eacute;sum&eacute;s and background verification records. Transactional and
              service-related details including order history, delivery and payment information,
              purchase or redemption records, customer assistance data, and enrolment-related
              information.
            </p>
            <h3>Legal Basis for Processing</h3>
            <p>
              We process personal data on the following legal bases, depending on the jurisdiction
              and nature of processing: To perform a contract or take steps prior to entering into a
              contract with you; Based on your consent; To comply with legal obligations; For
              legitimate business interests, including improving our Services, ensuring security,
              and preventing fraud, provided such interests do not override your rights. Where
              consent is required under applicable law, you may withdraw your consent at any time.
            </p>

            <h2>4. How We Store and Protect Your Information</h2>
            <p>
              The Information that you provide, subject to disclosure in accordance with this
              Privacy Policy, shall be maintained in a safe and secure manner. CleanStart databases
              and information are stored on secure servers with appropriate firewalls.
            </p>
            <p>
              CleanStart uses industry standard physical, technical and administrative security
              measures in accordance with all security standards required under applicable law to
              safeguard and keep secure your Information. We conduct periodic reviews of our
              security measures pertaining to our information collection and storage, to guard
              against unauthorized access to systems.
            </p>
            <p>
              Given the nature of internet transactions, CleanStart does not take any
              responsibility for the transmission of information including User Information shared
              by you. Any transmission of User Information on the internet is done at your risk and
              CleanStart shall not be responsible for the circumvention of the privacy settings or
              security measures either by you or any third party.
            </p>
            <p>
              When you enter User information (such as log in credentials) in respect of your User
              Account (&ldquo;User Information&rdquo;) or when you upload any Information through the
              use of the Platform, we take reasonable efforts to ensure that your User Information
              and all other information submitted by you is safe and secure; however, the Company
              makes no representation, warranties or other assurances that the security measures are
              adequate, safe, fool proof or impenetrable.
            </p>
            <p>
              As a User of the Services, you have the responsibility to ensure data security. You
              should use the Services responsibly and not share your User Information including your
              username or password or account information with any person. You are solely
              responsible for all acts done under the account registered to you.
            </p>
            <p>
              In the event of a personal data breach that is likely to result in risk to your
              rights or as required under applicable law, we will notify the relevant regulatory
              authority and/or affected individuals within the timelines prescribed under applicable
              law. We will take appropriate remedial steps to mitigate the impact of such breach.
            </p>

            <h2>5. Your Rights &amp; Preferences as a Data Subject</h2>
            <p>
              Depending on the jurisdiction and the applicable law, you may have certain rights
              regarding your personal information:
            </p>
            <h3>5.1 Singapore &mdash; PDPA</h3>
            <p>
              In line with Singapore&rsquo;s Personal Data Protection Act, you may have the
              following rights:
            </p>
            <table>
              <thead>
                <tr>
                  <th>Sl. No.</th>
                  <th>Right</th>
                  <th>Requirement</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1.</td>
                  <td><strong>Right to be informed</strong></td>
                  <td>You have a right to be informed about the manner in which any of your personal data is collected or used which we have endeavoured to do by way of this Policy.</td>
                </tr>
                <tr>
                  <td>2.</td>
                  <td><strong>Right of access</strong></td>
                  <td>You have a right to access the personal data you have provided by requesting us to provide you with the same.</td>
                </tr>
                <tr>
                  <td>3.</td>
                  <td><strong>Right to rectification</strong></td>
                  <td>You have a right to request us to amend or update your personal data if it is inaccurate or incomplete.</td>
                </tr>
                <tr>
                  <td>4.</td>
                  <td><strong>Right to object</strong></td>
                  <td>You have a right, at any time, to object to our processing of your personal data under certain circumstances.</td>
                </tr>
                <tr>
                  <td>5.</td>
                  <td><strong>Right to file a case / complaint</strong></td>
                  <td>You have the right to file a complaint with the respective data protection authority or institute civil proceedings against us, if you feel that your rights have been violated.</td>
                </tr>
              </tbody>
            </table>
            <h3>5.2 USA</h3>
            <p>
              Depending on the State in the USA in which you are located, you may have certain
              rights in accordance with the local data protection laws such as:
            </p>
            <ul>
              <li><strong>Right to know:</strong> You have the right to know about the personal information we have collected from you and the manner in which we use and share this information.</li>
              <li><strong>Right to notice:</strong> You have a right to be informed at or before the point of collection what categories of personal information will be collected and the purposes for which these categories will be used.</li>
              <li><strong>Right to correct:</strong> You have a right to request us to amend or update your personal data if it is inaccurate or incomplete.</li>
              <li><strong>Right to delete:</strong> You have the right to request us to delete the personal information we hold about you, subject to certain restrictions. We may have legal obligations to preserve certain data which could prevent us from deleting it.</li>
              <li><strong>Right to opt out of sale or sharing of data:</strong> You have the right to opt-out of us sharing your personal information. We do not sell any data of our users/customers/leads.</li>
              <li><strong>Right to limit:</strong> You have the right to direct us to use your sensitive personal information only for limited purposes.</li>
              <li><strong>Right to non-discrimination:</strong> We assure no discrimination against consumers exercising their right of privacy.</li>
            </ul>
            <h3>5.3 India</h3>
            <p>
              In accordance with the Digital Personal Data Protection Act, 2023, individuals located
              in India are entitled to the following rights with respect to their personal data,
              subject to the conditions and limitations prescribed under applicable law:
            </p>
            <ul>
              <li><strong>Right of access:</strong> You have the right to request access to a summary of your personal data processed by us, along with information regarding the processing activities undertaken.</li>
              <li><strong>Right to correction and erasure:</strong> You have the right to request correction of inaccurate or misleading personal data and the erasure of personal data that is no longer necessary for the purpose for which it was collected, subject to applicable legal requirements.</li>
              <li><strong>Right to withdraw consent:</strong> You have the right to withdraw your consent at any time for the processing of your personal data, provided that such withdrawal does not affect the lawfulness of processing carried out prior to such withdrawal.</li>
              <li><strong>Right to grievance redressal:</strong> You have the right to register a grievance with us in relation to the processing of your personal data. We shall endeavour to address such grievances within the timelines prescribed under applicable law.</li>
              <li><strong>Right to nominate:</strong> You have the right to nominate another individual to exercise your rights under the DPDP Act in the event of your death or incapacity.</li>
            </ul>

            <h2>6. Information We Collect Automatically</h2>
            <p>
              When you access or interact with our website, we automatically gather certain limited
              technical and usage-related information. This data does not directly identify you
              (such as your name or contact details), but may include information relating to your
              device and usage patterns.
            </p>
            <p>
              The information collected automatically includes: Analytics and Usage Data, including
              your public IP address associated with incoming HTTPS requests (such as image
              downloads), and information regarding your interactions with the website, such as
              timestamps of access, pages or files viewed, searches performed, and other actions
              undertaken, including the features you use. Online and Device Information, including
              browser type and configuration, device-related event data (such as system activity,
              error logs or crash reports, and hardware settings), operating system, language
              preferences, device name, and request and referral URLs. Location Information, limited
              to country-level location inferred from your IP address. We may collect this
              information directly through our website or by using web analytics tools and
              technologies, including cookies, web beacons, and similar tracking technologies.
            </p>

            <h2>7. Information We Share and Disclose</h2>
            <p>
              We share Information about you for the following operating and maintaining the
              Services:
            </p>
            <ul>
              <li><strong>To conduct Analytics:</strong> We use collective learnings about how people use our Services and feedback provided directly to us to troubleshoot and identify trends, usage, activity patterns and areas for integration and improvement. We may also share aggregated, pseudonymised information for compliance, industry and market analysis, demographic profiling, marketing and advertising, and other business purposes.</li>
              <li><strong>For Customer Support:</strong> We use your Information to resolve technical issues you encounter, respond to your requests for assistance, analyze crash information, and repair and improve the Services.</li>
              <li><strong>For Legal Reasons:</strong> We will also share Information with individuals or entities to the extent we believe in good faith it is required to ensure compliance with law/regulations and/or pursuant to enforceable orders of government, law enforcement or regulatory authorities; address fraud, security or technical issues; protect against harm to the rights, property or safety of the Product, its other users or the public as required or permitted by law.</li>
              <li><strong>For Effective Provision of Services:</strong> We may share your personal information with our employees, contractors and agents or our affiliates who need to know the information in order to provide Services to you and who are subject to strict contractual confidentiality obligations. We also share your personal information with our third-party service providers (website hosting, data analysis, IT and related infrastructure, customer service, email delivery, auditing, and other services).</li>
              <li><strong>Role as Data Processor:</strong> Where we process personal data on behalf of our Customers in connection with the provision of Services, we act as a data processor/service provider and process such personal data strictly in accordance with the applicable agreement entered into with the Customer and applicable data protection laws.</li>
            </ul>

            <h2>8. Third-Party Advertising</h2>
            <p>
              We use third-party advertising companies to serve advertisements regarding goods and
              services that may be of interest to you when you access and use the Services and other
              websites or online services. You may receive advertisements based on information
              relating to your access to and use of the Services and other websites or online
              services on any of your devices, as well as on information received from third
              parties. These companies place or recognize a unique Cookie on your browser
              (including through the use of pixel tags) and use these technologies, along with
              information they collect about your online use, to recognize you across the devices
              you use.
            </p>

            <h2>9. Information Retention</h2>
            <p>
              We will only keep your personal information for as long as it is necessary for the
              purposes set out in this Privacy Policy, unless a longer retention period is required
              or permitted by law (such as tax, accounting or other legal requirements). To
              determine the appropriate retention period, we consider the nature and sensitivity of
              the information, the potential risk of harm from unauthorized use or disclosure, the
              purposes for which we process the information, and any applicable legal requirements.
              When we have no ongoing legitimate business need to process your personal information,
              we will either delete or anonymize such information, or, if this is not possible,
              securely store and isolate it from any further processing until deletion is possible.
            </p>

            <h2>10. Transfer of Information</h2>
            <p>
              If you believe that we have not been able to assist with your complaint or concern,
              depending on the data privacy/protection law applicable in your country, you have the
              right to lodge a complaint with the competent supervisory authority.
            </p>
            <p>
              In order for us to facilitate our global operations, we may transfer and access the
              data we collect and process in accordance with this Policy to our group companies
              around the world. We implement appropriate safeguards for cross-border data transfers
              as required under applicable law, which may include contractual safeguards,
              regulatory-approved transfer mechanisms, or other lawful bases for transfer. By using
              our Service and providing your information, you consent to the transfer of your data
              to these international locations.
            </p>
            <p>
              We take appropriate measures to ensure the security and confidentiality of your
              personal information during international transfers. These measures may include
              entering into data transfer agreements based on requirements of relevant data
              protection authorities or ensuring that the recipients of your data are certified
              under recognized data protection frameworks.
            </p>
            <p>
              Further, in the ordinary course of business, we may employ other companies and people
              to assist us in providing certain components of our Services in compliance with the
              provisions of this Policy. To do so, we may need to share your data with them. We will
              ensure, through contractual agreements and other appropriate measures, that these
              third parties process your data in accordance with applicable data protection laws.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              For any privacy-related queries or complaints, you may contact our Grievance Officer /
              Data Protection Contact:
            </p>
            <ul>
              <li><strong>Name:</strong> Saurabh Jain</li>
              <li><strong>Email:</strong> <a href="mailto:legal@cleanstart.com">legal@cleanstart.com</a></li>
            </ul>

            <h2>12. Amendments</h2>
            <p>
              This Privacy Policy is subject to change from time to time. If we make changes to this
              Privacy Policy, we will update the &ldquo;Last Updated&rdquo; date at the top of this
              Privacy Policy. If you disagree with the revised Privacy Policy, you may delete your
              User Account and/or refrain from visiting the website.
            </p>
`,
  },
];
